### ISSUE TITLE
Manufacturer Information

### ISSUE THREAD

**Issue by kopacko** [digitalocean/netbox#1435] opened 2017-08-17 16:04 UTC
### Issue type: feature request

**Python version:**
**NetBox version:**

Would it be possible to get some fields created for the manufacturer page?

Support information (account number/support portal/etc)

Also the ability to create custom fields for the manufacturer page would be very nice as well.

**Comment by jeremystretch** [comment] 2017-08-17 16:44
This feature request lacks sufficient detail to be actionable. Per the [contributing guidelines](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md):

> When submitting a feature request on GitHub, be sure to include the following:
>
> * A detailed description of the proposed functionality
> * A use case for the feature; who would use it and what value it would add to NetBox
> * A rough description of changes necessary to the database schema (if applicable)
> * Any third-party libraries or other resources which would be involved

Please extend the request so that it meets all of  these requirements. If no response is received within a week, this issue will be closed.

**Comment by kopacko** [comment] 2017-08-17 18:22
Adding some basic fields to the manufacturer page, like a spot for support information specific to that manufacturer, the URL to the vendor support site, specific company credentials for support access, etc. All similar things provided under the Providers page, for example.

**When submitting a feature request on GitHub, be sure to include the following:**

- A detailed description of the proposed functionality

PROVIDER > SUPPORT INFO (Similar information for manufacturers)
--- Account number
--- Portal
--- Contact 

- A use case for the feature; who would use it and what value it would add to NetBox

USE CASE > Contacting Manufacturer Support (not needing to maintain a separate DB some place else with key support info.

- A rough description of changes necessary to the database schema (if applicable)

NOT A CLUE

- Any third-party libraries or other resources which would be involved

UNKNOWN (Don't think any third-party anything would be needed.)

Also, being able to add custom fields to any page. (I am not sure what else you need for that to be "actionable".)

Everything I have been mentioning/requested/etc has be summarily dismissed or blatantly no. These are all things that I am being asked of by my peers/bosses/etc or running into myself as we being using NetBox.

**Comment by jeremystretch** [comment] 2017-08-17 18:39
This sounds like a duplicate of #182. Please review that issue and add any additional comments there.

**Closed by jeremystretch** 2017-08-17 18:39 UTC
Labels: awaiting reply
