### ISSUE TITLE
Power options under racks and devices.

### ISSUE THREAD

**Issue by ksuuk** [digitalocean/netbox#1611] opened 2017-10-17 12:02 UTC
Please add Power options under racks and devices:

Racks:
Maximum allowed power usage  (watts) per rack
Power circuits: A, B , A+B
PDU A
PDU B

Devices:
Max power consumption (watts)
NR of PSU-s (1-10)
each PSU connection to PDU in rack ( A or B )

PSU: amount, list 1-10
Power consumption: W

And now when adding devices into racks, the racks total power consumption (based devices amount & power consumption) should be calculated and shown.

**Comment by jeremystretch** [comment] 2017-10-17 13:37
Duplicate of #54

**Closed by jeremystretch** 2017-10-17 13:37 UTC
