### ISSUE TITLE
not able to add interface

### ISSUE THREAD

**Issue by sacy80** [digitalocean/netbox#1345] opened 2017-07-14 06:09 UTC
### Issue type:
Not able to add interface on device.

Server Error
<type 'exceptions.AttributeError'>
This QueryDict instance is immutable

**OS version: CentOS7
**Python version:2.7.5
**NetBox version:V2.1-beta

**Comment by jeremystretch** [comment] 2017-07-14 12:55
Duplicate of #1334

**Closed by jeremystretch** 2017-07-14 12:55 UTC
