### ISSUE TITLE
NAT Assignment clears when editing IP address. 

### ISSUE THREAD

**Issue by tcope0094** [digitalocean/netbox#1289] opened 2017-06-19 14:34 UTC
### Issue type: Bug Report

**Python version:** 3.5
**NetBox version:** 2.0.7

When editing an existing IP address that has a NAT assignment, the NAT assignment clears when saving whatever changes are made. 

For instance I edited an IP address to change the description, saved my changes and the NAT assignment was gone after saving the description changes. 

So everytime I edit an IP address I have to add the NAT assignment back.

**Comment by jeremystretch** [comment] 2017-06-19 16:50
I'm not able to replicate this behavior. Could you please provide the list of steps needed to recreate the bug, beginning with creating a new IP?

**Comment by jeremystretch** [comment] 2017-06-28 17:02
Closing due to lack of activity.

**Comment by zevlag** [comment] 2017-07-03 16:04
I'm suggest we reopen this.  It happens for me too!
Python 2.7.9
v2.0.8-dev

When I view an IP with a NAT Address assigned it's there:
![screen shot 2017-07-03 at 9 55 42 am](https://user-images.githubusercontent.com/7240045/27800502-e2e1df5a-5fd6-11e7-8591-2b54ee12d808.png)

But when I click "Edit" on the IP address, the NAT details don't load, and thus when I click "Update" the NAT Assignment is lost.
![screen shot 2017-07-03 at 9 56 25 am](https://user-images.githubusercontent.com/7240045/27800530-076c01e8-5fd7-11e7-8bdd-a91c48948fd3.png)
![screen shot 2017-07-03 at 9 56 31 am](https://user-images.githubusercontent.com/7240045/27800529-07693210-5fd7-11e7-9eeb-98f086776ce3.png)

**Comment by zevlag** [comment] 2017-07-03 16:15
Step By Step

1AddFirstIP.png
2AddSecondIP.png
3ViewSecondIP.png
4EditSecondIP.png
5NATMissingSecondIP.png

![1addfirstip](https://user-images.githubusercontent.com/7240045/27800841-58b09d2e-5fd8-11e7-9395-6c3f5634294b.png)
![2addsecondip](https://user-images.githubusercontent.com/7240045/27800843-58c08720-5fd8-11e7-87b8-5593d8b2d28c.png)
![3viewsecondip](https://user-images.githubusercontent.com/7240045/27800845-58ca3a7c-5fd8-11e7-914d-359832665191.png)
![4editsecondip](https://user-images.githubusercontent.com/7240045/27800842-58bffdd2-5fd8-11e7-8500-61f202d66468.png)
![5natmissingsecondip](https://user-images.githubusercontent.com/7240045/27800844-58c1e0f2-5fd8-11e7-9c86-7daa65153963.png)

**Comment by jeremystretch** [comment] 2017-07-03 18:23
Thanks, will have a look.

**Comment by jeremystretch** [comment] 2017-07-05 17:00
To provide additional context: This occurs only when the inside NAT IP address is not assigned to a device/interface. The problem is that the chained select widgets in the form are not allowing the initialization of the assigned NAT IP.

**Closed** 2017-07-05 18:29 UTC
Labels: bug
