### ISSUE TITLE
Extensible Attributes for IPAM objects?

### ISSUE THREAD

**Issue by gkra** [digitalocean/netbox#193] opened 2016-07-05 17:22 UTC
One of the things we're leveraging in InfoBlox for our provisioning automation is the ability to add extensible attributes (key/value pairs) to objects in the IPAM data.

Currently, we define supernets for what we call "major" environments (i.e., Integration, QA, Staging, Production), under which we then provision "minor" environments per product group, such that no two products share a single subnet per environment. (Product A has it's own Integration subnet, separate from Product B's Integration subnet, both of which are contained within the Integration supernet.) To allow our provisioning automation to attach a VM to the correct subnet, it queries IPAM (InfoBlox) for the appropriate "minor" subnet matching a specific set of attributes. We then select the next free IP address, assign the IP to the hostname of the VM-to-be, and proceed with provisioning.

Likewise, when creating the "minor" environment subnets, we search for the appropriate "major" subnet via similar attribute sets, and then apply the correct attribute sets to the newly created subnet.

I've looked at #129 and #132, and this could possibly be a duplicate of #129, especially if custom fields could be added via API, once that's available. I don't think #132 would be sufficient on its own for our needs.

**Comment by jeremystretch** [comment] 2016-07-05 18:06
Marking this as a duplicate of #129.

**Closed by jeremystretch** 2016-07-05 18:06 UTC
Labels: duplicate
