### ISSUE TITLE
Ability to clone a device with a different name.

### ISSUE THREAD

**Issue by phobiadhs** [digitalocean/netbox#679] opened 2016-11-09 22:23 UTC
This is low priority but still important in my eyes as adding the device manually isn't exactly difficult. As it is now though, it takes many repeating clicks to assign the required fields for each new device assuming you are creating many similar devices.

What I suggest is the ability to clone a device, replicating Device Role, Manufacturer and Device Type all by default.

Obviously a new Name will be required and I believe when that name is entered, the ability to select a site and rack should also be available, likely with the defaults being the cloned devices values.

This could save a good number of clicks and/or tabs for each similar device entry and make the overall workflow considerably more efficient when adding many new similar devices.

**Comment by jeremystretch** [comment] 2016-11-10 20:40
To clarify, you're asking for the ability to select a device that has already been created, and pre-populate most of its data in a form to create a new device?

(This is probably related to #648, but that deals only with creating multiple devices in immediate succession.)

**Comment by phobiadhs** [comment] 2016-11-10 22:21
You are correct.
 
I would like to select a device, hit a "Clone" button and have the above mentioned fields be pre populated in the new device with only the name and the rack left to manually enter or select. 

As the point of this enhancement is to increase efficiency in workflow, I would suggest that the cloned fields are handled in the background so the user doesn't get bogged down in the details of a cloned device as it is being created. Fill in Name, select Rack. Presto, cloned device created.

Looking at #648, they are related but the usage is a bit different as you said.

**Comment by soamz** [comment] 2016-11-12 11:28
Still confused. 
How do we clone ?

I checked #648, did not understand.

**Comment by jeremystretch** [comment] 2016-11-22 19:51
This actually seems to be a duplicate of #33.

**Closed by jeremystretch** 2016-11-22 19:51 UTC
Labels: enhancement
