### ISSUE TITLE
VLAN Groups Not Populating

### ISSUE THREAD

**Issue by engageant** [digitalocean/netbox#1742] opened 2017-11-29 16:59 UTC
### Issue type
[ ] Feature request 
[ X] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.2.6

### Description
I am having issues with VLAN groups:

1. I cannot assign a prefix to a vlan that's in a vlan group, only to those not in a group.  It lets me select the site, but the group and vlan listboxes are empty, despite the sites having groups assigned.
To reproduce: Add a new prefix. Select a site.  The VLAN group listbox does not populate (and understandably, neither does the VLAN listbox).
2. When editing an existing prefix that's assigned to a vlan group, the group is shown correctly, but you cannot change it.  Same as before - you can select a site but the group and vlan listboxes are empty.
To reproduce: edit an existing prefix.  Select a different site.  The VLAN group listbox does not populate (and understandably, neither does the VLAN listbox).
3. I cannot add a vlan to a vlan group. Same symptoms.
To reproduce: edit a vlan.  Select a site.  The group listbox does not populate.

I tried creating a new site, group, and vlan, and have the same issue.  As an aside, I can't figure out how to delete the test site I created.

**Comment by jeremystretch** [comment] 2017-11-29 19:04
Please post the exact steps that can be taken to reproduce the issue you're seeing.

**Comment by engageant** [comment] 2017-11-29 19:14
@jeremystretch I updated the OP.

**Comment by jeremystretch** [comment] 2017-11-29 19:22
> To reproduce: Add a new prefix. Select a site. The VLAN group listbox does not populate (and understandably, neither does the VLAN listbox).

Works for me. Do you have one or more VLAN groups assigned to the site? Is the API call being made by the browser when a site is selected? If so, what response is being returned?

**Comment by engageant** [comment] 2017-11-30 20:00
@jeremystretch yes, the sites have valid groups.  Something broke somewhere along the way, as there are older groups properly assigned to sites.  This is essentially issue 2 in my OP - the existing group is shown, but you can't select a different one.  How do I check if the API call is made, and what the response is?

**Comment by jeremystretch** [comment] 2017-12-01 14:16
@engageant In Firefox or Chrome, you can press F12 to bring up the developer console. Select the network tab, then select a site from the list. You should see the HTTP request recorded under the tab, as well as its response.

**Comment by engageant** [comment] 2017-12-01 18:20
@jeremystretch here's what comes back in the response for the edit page the first time:
```
  <select name="site" placeholder="None" filter-for="group" nullable="true" id="id_site" class="form-control">
  <option value="">---------</option>
  <option value="7">Site7</option>
  <option value="4">Site4</option>
  <option value="3" selected>Site3</option>
  <option value="5">Site5</option>
  <option value="2">Site2</option>
  <option value="11">Site11</option>
  <option value="9">Site9</option>
  <option value="1">Site1</option>
  <option value="8">Site8</option>
  <option value="6">Site6</option>
</select>         
<select name="group" placeholder="Group" class="api-select form-control" api-url="/api/ipam/vlan-groups/?site_id={{site}}" id="id_group">
  <option value="">---------</option>
  <option value="2" selected>Site3 VLANs</option>
</select>
```
When I then change the site selection, this appears in the Console:

```
Uncaught TypeError: Cannot read property 'id' of null
    at forms.js?v2.2.6:127
    at Function.each (jquery-3.2.1.min.js:2)
    at Object.success (forms.js?v2.2.6:126)
    at i (jquery-3.2.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.2.1.min.js:2)
    at A (jquery-3.2.1.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-3.2.1.min.js:4) 
```

**Comment by jeremystretch** [comment] 2017-12-05 19:20
Ok, but what is the request being made to the API and what is the response being received? Look under the "network" tab?

**Comment by engageant** [comment] 2017-12-05 19:45
Maybe this helps? This is when I choose a different site when editing a
VLAN.
[image: image.png]
And here's the response:

{"count":1,"next":null,"previous":null,"results":[{"id":2,"name":"my site
VLANs","slug":"my-site-vlans","site":{"id":3,"url":"
http://sc-netbox-01/api/dcim/sites/3/","name":"my site","slug":"my-site"}}]}

**Comment by jeremystretch** [comment] 2017-12-08 16:44
Maybe you're running outdated Javascript. Did you run `manage.py collectstatic` as part of the last upgrade?

**Comment by engageant** [comment] 2017-12-08 16:47
I have two Netbox instances that are both on the same version and one works
while the other doesn't.  I'm beginning to think that something is up with
the DB in the non-working one. I don't recall ever running that command;
when I upgrade I follow the process for cloning the repo at
https://netbox.readthedocs.io/en/latest/installation/upgrading/

**Comment by jeremystretch** [comment] 2017-12-08 19:31
`manage.py collectstatic` is performed by the `upgrade.sh` script, so you shouldn't need to do it manually if you've been running the script. Maybe try it on the server with issues though and see if it helps.

**Comment by engageant** [comment] 2017-12-11 19:22
0 static files copied to '/opt/netbox/netbox/static', 264 unmodified.

**Comment by jeremystretch** [comment] 2017-12-13 20:20
@engageant Sorry, don't know what else to look at. Maybe post on the mailing list and see if anyone has any ideas?

Going to close this out now since we can't positively identify this behavior as a reproducible bug.

**Closed by jeremystretch** 2017-12-13 20:20 UTC
Labels: awaiting reply
