### ISSUE TITLE
Having Clone feature

### ISSUE THREAD

**Issue by mabazyar** [digitalocean/netbox#1967] opened 2018-03-09 23:25 UTC
### Issue type
[X] Feature request 
[] Bug report     
[ ] Documentation   

### Environment
* Python version: 3.5.2
* NetBox version:  v2.3.1

### Description
It would be nice if we had clone feature in place to carry over what we have already done on a record. If it was in place, all we would need to do is that tweaking the entries in cloned record and get that submitted with different name.

In fact, that exactly what we do in Zabbix.

**Comment by cimnine** [comment] 2018-03-12 16:53
I think you can use the import/export functionality to mimic this.

**Comment by jeremystretch** [comment] 2018-03-12 17:51
Sounds like a duplicate of #33

**Closed by jeremystretch** 2018-03-12 17:51 UTC
