### ISSUE TITLE
enhancement to support proxied devices

### ISSUE THREAD

**Issue by jeremyschulman** [digitalocean/netbox#1856] opened 2018-02-01 19:49 UTC
### Issue type
[X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  all
* NetBox version:  2.2.8

### Description

As a User of Netbox that wants to inventory devices managed by a 3rd-party controller system (aka a "proxy device"), I would like to associate the proxy information to the device instance, and then provide that proxy information to the NAPALM driver as part of the `optional_args` so that
the driver can make the necessary connection / communications using that information.

**Comment by jeremyschulman** [comment] 2018-02-01 19:53
I would like to propose the following approach making use of `custom_fields` bound to the device instance.  Any custom field that begins with "napalm_option" will be passed to the napalm driver, in addition to any existing napalm settings stored as part of the netbox configuration.  

For example, if the custom_fields for a device contained the items:
```python
napalm_option_server = http://my-proxy-server.com
napalm_option_token = blurbidyblugyakkettytoken
```

Then, at the time when Netbox makes the call to the napalm driver, [here](https://github.com/digitalocean/netbox/blob/develop/netbox/dcim/api/views.py#L297), these key-value
pairs would be passed to the napalm_driver code.

**Comment by jeremystretch** [comment] 2018-02-13 18:48
Let's avoid trying to hotwire any features by designating special custom field names. I want to ensure custom field names are kept decoupled from any built-in functionality.

**Comment by orgito** [comment] 2018-06-26 00:39
We could add napalm_optional_args to the device model as suggested for the platform model. The optional_passed to the napalm_driver would com from settings NAPAL_ARGS -> napalm_optional_args platform field -> napalm_optional_args device field. 
I could update #2190 to also include this.

**Comment by jeremystretch** [comment] 2019-06-25 15:43
Doesn't look like this ever got any traction, and honestly I still don't have any good ideas for implementing it. Going to close it out; might be something we revisit in the future.

**Closed by jeremystretch** 2019-06-25 15:43 UTC
Labels: help wanted
