### ISSUE TITLE
Can't delete device or connection after a mistake

### ISSUE THREAD

**Issue by hugleo** [digitalocean/netbox#2685] opened 2018-12-12 19:05 UTC
### Environment

* Python version:  3.5.3
* NetBox version:  Example: 2.5.0

### Steps to Reproduce

1) Create a device (I named Device-Test)
2) Create another device (I named Device-Test2)
3) Create a interface for Device-Test (I named eth0)
4) Create a Rear Port for Device-Test2 (I named reartest)
5) Click on Device-Test2 and find the reartest Rear Port and then try make a connection.
We'll receive the error: 
<class 'dcim.models.FrontPort.DoesNotExist'>
FrontPort matching query does not exist.

6) After that is impossible to delete the created connection neither the whole device. Keeping showing that FrontPort.DoesNotExist error and deletion doesn't complete. So I'm stuck with that device and connection forever. 

### Expected Behavior

Need a way to revert back so I can delete the wrong connection that a created by mistake.

### Observed Behavior

Deletion doesn't complete.

![conection](https://user-images.githubusercontent.com/4573505/49892407-0aed2880-fe30-11e8-9212-0cc75a123ff8.png)
![candelete](https://user-images.githubusercontent.com/4573505/49892408-0b85bf00-fe30-11e8-9248-f72375cad74b.png)
![error](https://user-images.githubusercontent.com/4573505/49892410-0b85bf00-fe30-11e8-93fb-d2b68aa3fa64.png)

**Comment by jeremystretch** [comment] 2018-12-12 21:41
Duplicate of #2683

**Closed by jeremystretch** 2018-12-12 21:41 UTC
Labels: status: duplicate

**Comment by hugleo** [comment] 2018-12-15 12:50
upgraded to 2.6.1 and same error yet. If follow my steps to reproduce we'll get the error:

<class 'dcim.models.FrontPort.DoesNotExist'>

FrontPort matching query does not exist.
