### ISSUE TITLE
Double sided circuits

### ISSUE THREAD

**Issue by markve-sa** [digitalocean/netbox#462] opened 2016-08-12 14:11 UTC
Circuits currently only allow one side. All of our links are 3rd party P2P layer 2 circuits or dedicated dark fibre. We own the equipment on both sides of the circuit, it would be quite useful to be able to add both sides to a circuit.

**Comment by jeremystretch** [comment] 2016-08-12 14:13
Duplicate of #49

**Closed by jeremystretch** 2016-08-12 14:13 UTC
