### ISSUE TITLE
Allow creation of Notes/Comments for Device Types

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#122] opened 2016-06-29 19:29 UTC
Use case, for a PDU I want to document the NEMA plug style, number and style of outlets on PDU and possibly other common information for easy reference

As devices already have comments themselves, it might be nice to have devices show their own comments and then have the device type comments be visible as well (another box I guess)

So for that PDU device type I'd have the common notes and then for the speific device I could notate when I flash the firmware, etc

**Comment by jeremystretch** [comment] 2016-09-14 15:22
I'm hesitant to add any sort of comment capability to device types because I fear it will encourage users to create duplicate, nonstandard device types. For instance, if I define a Juniper EX4300-48T device type, it should not be necessary to convey any additional information about it, since it represents exactly one iteration of a real physical device. I don't want to lead users into a situation where they might create (for example) one instance of the device type without an expansion card and another instance with an expansion card.

Additionally, I'd like to start creating standard device type definitions as described in #451, which might alleviate the need for any custom comments.

Your specific use case, regarding annotating power outlet details, is probably best addressed by extending the power connection models to include voltage, form factor, etc. It's been my intention from early on to eventually extend power outlets to include this information; I just never got around to it. (Honestly I'm surprised this hasn't been more in demand.)

**Comment by drybjed** [comment] 2016-10-27 07:04
(I'll reply here since my related issue was a duplicate of this issue.)

My use case for the device type comments is to add custom information about a particular set of devices , say an URL to the manufacturer's firmware download page, which then could be easily referenced from the particular device page if needed. Right now, if I have for example a set of 50 Juniper switches, I can either add an URL to each device comment field, one at a time, or keep a duplicate database of device types somewhere else. Having a way to add custom information to a device type would make the requirement of an additional database irrelevant.

Alternatively, I tried to add at least a custom field to a device type which could hold an URL to a wiki page which could contain additional information, but unfortunately there's no way to add custom fields to device types, only devices. So the problem remains the same.

I hope that you reconsider your decision about this issue. If you really don't want to add a free form comment field to device types, I think that at least an additional field which could hold an URL to somewhere else with more information would greatly benefit the NetBox usability.

**Comment by jeremystretch** [comment] 2016-12-16 15:58
#722 was just completed to enable custom fields for device types. We can probably add a comments field as well.

**Closed** 2016-12-16 16:14 UTC
