### ISSUE TITLE
FrontPort matching query does not exist.

### ISSUE THREAD

**Issue by Bosni1** [digitalocean/netbox#2683] opened 2018-12-12 17:09 UTC
### Environment
* Python version:  3.5.3
* NetBox version:  2.5.0

### Steps to Reproduce
I have a transport switch that has a OC48 card inside a device bay with two SC fiber ports in the rear. I created 4 rear port components to represent 2 RX and TX ports each. When I attempt to connect a cable to a patch panel that also has front and rear ports built.

### Expected Behavior
Cable successfully connects to both ports.

### Observed Behavior
I get the following error:
<class 'dcim.models.FrontPort.DoesNotExist'>

FronPort matching query does not exist.

**Comment by hugleo** [comment] 2018-12-12 19:20
Duplicate of #2685

**Closed** 2018-12-12 21:40 UTC
Labels: status: accepted, type: bug
