### ISSUE TITLE
Rack Layout, iOS style Drag and Drop editing

### ISSUE THREAD

**Issue by jvanderaa** [digitalocean/netbox#2505] opened 2018-10-08 14:29 UTC
### Environment
* Python version:  3.6
* NetBox version:  2.3.7

### Proposed Functionality
iOS like `Edit` and then drag and drop reordering of a rack. 

> Not an urgent feature request.

### Use Case

Right now if you added a bunch of devices to rack, then you want to move all of the devices (say during rack planning) you have to go edit each device. If there is the capability to do iOS like edit function where the devices can be dragged around, that can be helpful. This is something that would need a button to edit the rack, not just available immediately upon viewing in case of accidental click and moving.

### Database Changes
Not aware of any

**Comment by jeremystretch** [comment] 2018-10-08 14:31
Duplicate of #124. No plans to implement this any time soon as it will require reworking the entire frontend.

**Closed by jeremystretch** 2018-10-08 14:31 UTC
