### ISSUE TITLE
Ability to add IP-Regions to Prefixes

### ISSUE THREAD

**Issue by larsuhartmann** [digitalocean/netbox#1521] opened 2017-09-20 14:54 UTC
### Issue type
[x] Feature request
[ ] Bug report
[ ] Documentation

### Environment
* Python version:  3.4.5
* NetBox version:  2.2-beta1

### Description
It would be nice to be able to add blocks of IPs to a Prefix without it showing up as multiple single IP Addresses in on the /ipam/prefixes/i/ip-addresses/ overview - this would be extremely handy while adding DHCP blocks or just reserved areas to Prefixes.

Right now i can add multiple IPs but i end up with something like this:
![image](https://user-images.githubusercontent.com/76582/30650883-4f04abb4-9e24-11e7-9011-49ff8f4b3051.png)

Thanks in Advance

Cheers
Lars

**Comment by jeremystretch** [comment] 2017-09-20 14:56
Duplicate of #834

**Closed by jeremystretch** 2017-09-20 14:56 UTC
