### ISSUE TITLE
[Feature Request] Rack reserved by tenant

### ISSUE THREAD

**Issue by Mattallmighty** [digitalocean/netbox#510] opened 2016-08-26 01:50 UTC
Hi Jeremy,

I would like to request reserving rack space to a tenant. 
I can assign a full rack to a tenant, but I require more information to assign/reserve RU that are not currently in use.

For example, 'company A' has purchased half a rack, and currently only using 2RU. 
I need a way to identify that 'company A' has reserved rack: M1-4A-02 from 1RU to 15RU.

It would be good for us have an indication when you hover mouse point over the greyed out area there is information stating there is already a tenant ('company A') assigned to the reserved rack space.

Thanks
Matt

**Comment by jeremystretch** [comment] 2016-08-30 15:28
Duplicate of #36

**Closed by jeremystretch** 2016-08-30 15:28 UTC
