### ISSUE TITLE
Add change log to objects

### ISSUE THREAD

**Issue by xonacs** [digitalocean/netbox#2183] opened 2018-06-20 07:39 UTC
[X] Feature request
[ ] Bug report     
[ ] Documentation  

* Python version:  2.7.5
* NetBox version:  2.3.4

Currently any changes to any part of the system are logged and can be seen on the Django administration panel.  It would be benificial to users and admins alike if each item on netbox would have a change log within its own window showing who created and who updated an item throughout its lifetime (similar to how pfSense does it).

As this information already is collected and exists it should be able to be read and listed.

**Comment by jeremystretch** [comment] 2018-06-20 13:21
Duplicate of #1898

**Closed by jeremystretch** 2018-06-20 13:21 UTC
