### ISSUE TITLE
Support Device groups and vlans per device/device group

### ISSUE THREAD

**Issue by loganbest** [digitalocean/netbox#90] opened 2016-06-28 20:41 UTC
Ideally we'd like to have the ability to group devices together and have Unique vlans per device or device group.

In a traditional campus network topology you have core -> distribution -> access. Often times you have router pairs at core/distro layers and HSRP/GLBP on those pairs. Supporting a unique Vlan 500 on distrogrp1 (distro1a/distro1b) and a unique Vlan 500 on distrogrp2 (distro2a/distro2b) would be ideal in many implementations of this software. Each unique Vlan can have it's own associations as they currently do.

**Comment by bellwood** [comment] 2016-06-29 02:48
We do something similar:

Juniper Edge -> VSRP -> Cisco Distribution -> HSRP -> Cisco Core

For our distribution groups we prefix the vlans by the group number so everthing in group one has a vlan 1xx, group 2 vlan 2xx and so on

HSRP version 2 gives you almost endless possibilities

**Comment by mpenning** [comment] 2016-06-30 09:15
@jeremystretch seems to have made a duplicate of this request in issue #111

**Comment by peelman** [comment] 2016-06-30 20:11
#99 might tie into this too; being able to logically link/group devices for the purposes of stacking, high availability, etc.

**Comment by jeremystretch** [comment] 2016-07-29 14:08
Seems like this was implemented by #111.

**Closed by jeremystretch** 2016-07-29 14:08 UTC
Labels: duplicate
