### ISSUE TITLE
issue with displaying devices

### ISSUE THREAD

**Issue by chagara** [digitalocean/netbox#511] opened 2016-08-26 12:31 UTC
I tried to search if the new versions fix this but, did not see anything. When I look all my devices the fields end up behind the search feature in the right. So behind the search box, you can see IP's cut out. At the moment I can't put a screenshot. I'm using version 1.4.2, chrome 50.0.2661.94.

**Comment by jeremystretch** [comment] 2016-08-30 15:27
Please provide a screenshot.

**Comment by jeremystretch** [comment] 2016-08-30 15:32
Duplicate of #507

**Closed by jeremystretch** 2016-08-30 15:32 UTC
Labels: awaiting reply
