### ISSUE TITLE
Circuit Terminaison with 2 sides

### ISSUE THREAD

**Issue by thoms27** [digitalocean/netbox#639] opened 2016-10-26 12:40 UTC
Hi,

Working for an ISP, a circuit has 2 sides ofr us. Side A, which represent le customer end (CPE router), and side B which represent the ISP side (PE Collect router).

Is it possible to add 2 terminaisons but not necessarily ?

Thanks in advance.

Thomas V.

**Comment by jeremystretch** [comment] 2016-10-26 13:02
Duplicate of #49

**Closed by jeremystretch** 2016-10-26 13:02 UTC
Labels: duplicate
