### ISSUE TITLE
802.1ad (AKA: QinQ, Service Tag)

### ISSUE THREAD

**Issue by cre8rnz** [digitalocean/netbox#1324] opened 2017-07-09 18:52 UTC
Any chance we can reopen this? 802.1ad is being used more and more ..
We have to use VRFs for IPs and VLAN Groups to do this currently and it makes things a tad messy for us.
Not sure how complex it would be to effectively duplicate the VLAN functions, Call it ServiceTAG, make it all masters for vlans and add a new column for ServiceTAG under vlans?

[https://github.com/digitalocean/netbox/issues/116](Enable creation of QinQ VLANs #116l)
[https://github.com/digitalocean/netbox/issues/777](VLAN “Service Identifier” field (VXLAN or ISID) #777l)

**Comment by jeremystretch** [comment] 2017-07-10 13:23
Duplicate of #116. Please avoid opening new issues for topics which have already been addressed.

**Closed by jeremystretch** 2017-07-10 13:23 UTC

**Comment by cre8rnz** [comment] 2017-07-11 19:24
.. Yes aware it was a duplicate. That is why I included it in my post..
I had asked the above question in the post you linked to also.
I had no answer on this topic which you obviously have seen as you linked to this post...

So I guess your answer is no, even though you didn't answer my actual question (or consider it obviously).
Even a No I don't want to implement this as it seems too hard like your original answer would have been fine.

**Comment by cre8rnz** [comment] 2017-07-19 03:16
Hi Jeremy,

Not sure why you have deleted my previous comment, however...
I had a college ask me what was the outcome of this so thought I would ask again.
Is there anyway we can re-open an issue (for discussion among yourself and other users) that has been addressed without it being closed before discussion?

There was a good few people interested in this in the beginning (Which I have linked to in my original post). And I imagine with all of the active users now there may be more interest ?

**Comment by cre8rnz** [comment] 2019-08-29 07:28
Hey Guys,
Have had 2 more people say +1 for reopening on the following; https://github.com/netbox-community/netbox/issues/116
Those comments were deleted and the issue has been closed.
Seems people are after this as an option.

Any plans to add this at any stage?

Thanks

**Comment by cre8rnz** [comment] 2019-08-29 07:29
FYI Also have https://github.com/netbox-community/netbox/issues/1725 and https://github.com/netbox-community/netbox/issues/1800 and https://github.com/netbox-community/netbox/issues/2800 related to this.

Thanks
