### ISSUE TITLE
Custom form-factors

### ISSUE THREAD

**Issue by uncleVALERA** [digitalocean/netbox#2268] opened 2018-07-24 15:24 UTC
**Issue type**
[X] Feature request
[ ] Bug report
[ ] Documentation

**Environment**
Python version: 3.5.2
NetBox version: 2.3.6

**Description**
As i can see you have hardcoded form-factors.
I think that better way might have possibility  creating custom form-factors. And customer could make needed type of interface. You need just make code for check that type of interface one device corresponds  type of interface second device.

**Comment by jeremystretch** [comment] 2018-07-24 15:31
Duplicate of #84

**Closed by jeremystretch** 2018-07-24 15:31 UTC
