### ISSUE TITLE
Cannot assign IP to tty ports for console server

### ISSUE THREAD

**Issue by snoopytrb** [digitalocean/netbox#995] opened 2017-03-24 16:45 UTC
Trying to attach an IP address to a tty interface on our console server but netbox only shows the first tty interface in the drop down, there are 16 total tty interfaces.

For example.
1. Created console server device
2. Added tty0/1/1 through tty0/1/15 using "add console server ports"
3. on Console server device page click "Assign IP Address"
4. Input all IP address info, only tty0/1/0 is listed in interface drop down ,tty01/1-15 are missing.

Problem is also visible after creating an IP address and clicking on "Assign" on IP Address page, cannot see tty0/1/1-15 in Interface dropdown after selecting Console Server.

**Python version: 2.7**
**NetBox version: 1.9.3**

**Comment by jeremystretch** [comment] 2017-03-24 19:00
This is intended behavior. IP addresses can only be assigned to interfaces. (Interfaces represent network connections; console ports represent serial console connections.)

**Comment by snoopytrb** [comment] 2017-03-25 22:19
If intended behavior is not being able to assign an IP to a tty then there is a definitely a bug that allows assigning an IP to tty0/1/0 as I've already successfully done that, the others aren't visible in the list as intended.

**Comment by jeremystretch** [comment] 2017-03-27 13:25
You've created tty0/1/0 as an interface, rather than as a console server port. I'm going to close this as there's nothing actionable.

**Closed by jeremystretch** 2017-03-27 13:25 UTC
