### ISSUE TITLE
Feature request: Have a history log in servers.

### ISSUE THREAD

**Issue by marc-us** [digitalocean/netbox#1020] opened 2017-03-30 16:44 UTC
Hi,

I would like to extend the server view with history logging capability.
The usecase is to keep track what happen with server in past.
Like: cabling change, IP assignment, HW expansion etc.

For the beginning I would like to make it available as a free text form. (timestamp, tag, author, description) The tags should be implemented like server roles. In view It will be a separate tab like inventory items.

Later I would like to extend it with automated comments, like when the IP was assigned, changed any field etc. which is now available just on dashboard, without any filtering possibility.

If you need this, I can share with the community. If not I will keep it in our repo.

Regards,
Mark

**Comment by marc-us** [comment] 2017-03-30 17:25
Not so much, check my modell.py:
`+class HistoryLog(models.Model):
+    """
+    A history is a free text form which gives capability to store any comment or change in time based view.
+    """
+    time = models.DateTimeField(auto_now_add=True, editable=False)
+    user = models.ForeignKey(User, related_name='actions', on_delete=models.CASCADE)
+    device = models.ForeignKey('Device', related_name='history_log', on_delete=models.CASCADE)
+
+    role = models.ForeignKey('HitoryRole', related_name='history', blank=True, null=True, on_delete=models.PROTECT)
+    message = models.TextField(blank=True)
+
+    class Meta:
+        ordering = ['-time']
+
+    def __str__(self):
+
+
+@python_2_unicode_compatible
+class HistoryRole(models.Model):
+    """
+    Grouping the history activity type
+    """
+    name = models.CharField(max_length=50, unique=True)
+    slug = models.SlugField(unique=True)
+    color = ColorField()
+
+    class Meta:
+        ordering = ['name']
+
+    def __str__(self):
+        return self.name`

**Comment by jeremystretch** [comment] 2017-03-30 17:54
Duplicate of #151

**Closed by jeremystretch** 2017-03-30 17:54 UTC
