### ISSUE TITLE
Secrets for Virtual Machines

### ISSUE THREAD

**Issue by martink2** [digitalocean/netbox#1596] opened 2017-10-15 21:05 UTC
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.12
* NetBox version:  2.2.1

### Description
The current VM model does not support Secrets to be associated with VM's.

From an administrative standpoint a VM is no different from a Physical Server (except the missing HW of cause) so it would be highly desirable  to also save Credentials and Secrets with the VM Object.

This might be considered a duplicate of #1503 though i would say that secrets are rather more essential on VM's as they are on additional objects.

**Comment by jnfohr** [comment] 2017-10-16 07:06
I have the same needs on my side, the virtualization handling within netbox is a great feature but the secrets for VMs are mandatory for us.

Regards

**Comment by kasimon** [comment] 2017-10-16 07:57
Instead of implementing a dedicated security storage for netbox, probably adding integration to store secrets in hashicorp vault (https://vaultproject.io) would be a good solution.

**Comment by martink2** [comment] 2017-10-16 11:42
@kasimon the same was suggested already in #1503 so maybe you can open a separate Feature request this is more for which objects secrets are needed than how they are stored backend wise.

**Comment by kasimon** [comment] 2017-10-16 12:26
@martink2 thank your for the pointer.

**Comment by jeremystretch** [comment] 2017-10-16 13:12
This is a duplicate of #1495, which was folded into #1503.

**Closed by jeremystretch** 2017-10-16 13:12 UTC
