### ISSUE TITLE
Unable to set tenant when creating objects

### ISSUE THREAD

**Issue by martink2** [digitalocean/netbox#1228] opened 2017-05-25 14:22 UTC
Python version:v2.7
NetBox version:v2.0.3

Since the latest upgrade I can no longer set the tenant on any object i 
add to Netbox via the create object(tested with IP's, Devices, Racks, 
Subnet's). The Drop Down is not populated with any of my tenants.

When importing from CSV i can set the tenant just fine. Also it
is possible to set the tenant on objects when using bulk operations.

 Thanks

Martin

**Comment by jeremystretch** [comment] 2017-05-25 14:24
Please provide the list of steps necessary to reproduce this behavior.

**Comment by martink2** [comment] 2017-05-25 14:29
Click "IP Space" -> "Add a Prefix" (url-path /ipam/prefixes/add/)
Expected Behavior: Tenant Dropdown Populated with Tenants
Observed Behavior: Tenant Dropdown contains only "---------"

This is the case for all objects not just Prefixes.

**Comment by jeremystretch** [comment] 2017-05-25 15:29
I'm not able to reproduce this problem on the current develop branch (2.0.4-dev). It looks like it may have been fixed by 6719578f1433efb994f5274b5a8da7beae387070 for #1212.

I'll close this issue for now with the assumption that it is fixed in 2.0.4, but please comment here again if you continue to experience problems after the 2.0.4 release.

**Closed by jeremystretch** 2017-05-25 15:29 UTC

**Comment by martink2** [comment] 2017-05-25 15:40
Thanks, i pulled in the commit and it fixes the issue.
