### ISSUE TITLE
Allow LAG to span over multple Devices (evpn multihoming)

### ISSUE THREAD

**Issue by spolack** [digitalocean/netbox#3033] opened 2019-04-01 10:21 UTC
### Proposed Functionality
A LAG could span over multiple devices. There should be a way to model this in Netbox. As LAG interface names could differ across devices (i.e. ae0 on Device A, ae25 on Device B) we should be able to link LAG interfaces somehow, so they could share VLANS, tags and mtu and other properties.

### Use Case
In order to model "eVPN multihoming", we'd like to span a LAG over multiple devices in Netbox. This would be also useful to model MC-LAG.

### Database Changes
This could be accomplished by implementing  a virtual parent lag interface, which is not assigned to any device. LAG interfaces could reference to that virtual parent lag interface.

**Comment by lampwins** [comment] 2019-04-02 01:45
While I know you mention EVPN, from a modeling standpoint this would be the same as MLAG which would be a duplicate of https://github.com/digitalocean/netbox/issues/2830

**Closed by lampwins** 2019-04-02 01:45 UTC
Labels: status: duplicate

**Comment by spolack** [comment] 2019-04-02 10:22
> The multichassis functionality is accomplished by proprietary hacks performed on the forwarding plane, which vary in their implementation among platforms and are out of scope for NetBox.
This is not the case with evpn - Thats non-proprietary and shouldnt be considered as a hack, although it might look like that from a tradional network engineer perspective.


Please reevalute this, as EVPN + Multihoming will definately become a topic in near future.
