### ISSUE TITLE
Rack Elevetions stop working after update

### ISSUE THREAD

**Issue by kstinster** [digitalocean/netbox#2829] opened 2019-01-30 19:39 UTC
### Environment
* Python version:  3.5.2
* NetBox version: 2.5.4

**Rack Elevation stop working after update from 2.3.1 to 2.5.4**

### Steps to Reproduce
1.  Select Rack Elevation in WEB GUI and got an error
"Internal Server Error: /dcim/rack-elevations/
TemplateDoesNotExist at /dcim/rack-elevations/
dcim/inc/filter_rack_group.html"

 The same problem reported in mailing list https://groups.google.com/forum/#!topic/netbox-discuss/dHeiDndXbk4

**Comment by jeremystretch** [comment] 2019-01-30 19:46
Duplicate of #2824

**Closed by jeremystretch** 2019-01-30 19:46 UTC
