### ISSUE TITLE
Ability to upload documents / manuals such as PDF for devices

### ISSUE THREAD

**Issue by jameswhite4684** [digitalocean/netbox#3089] opened 2019-04-18 18:50 UTC
### Environment
* Python version:  
* NetBox version:  

### Proposed Functionality
Ability to upload technical documents / manuals to a device (Similar to images). 

### Use Case
Ability to easily store and retrieve technical information from the device device screen. Such as whitepapers, technical manuals, etc. This would allow easy retrieval of information. This would help current network admins and future network admins in a situation a seperate document server needs to be created or shared folders and trying to keep up with documents.

**Comment by jeremystretch** [comment] 2019-04-18 20:53
Duplicate of #1408

**Closed by jeremystretch** 2019-04-18 20:53 UTC
