### ISSUE TITLE
Exception when connecting power outlet

### ISSUE THREAD

**Issue by jwegner89** [digitalocean/netbox#1322] opened 2017-07-07 22:36 UTC
### Issue type: bug report

**Python version:** 3.4.5
**NetBox version:** 2.0.8

Updated from release 2.0.4 to 2.0.8. The service started normally, and I was able to perform other tasks without issue, e.g. adding prefixes, etc. I created a PDU from template (so it has the correct number of ports, etc) and clicked on the "connect" button when the exception detailed in [power_outlet_exception.txt](https://github.com/digitalocean/netbox/files/1132489/power_outlet_exception.txt) was thrown. 

The system in RHEL 7.3 x86_64, with an NGINX 1.10.2 webserver proxying to a uWSGI 2.0.14 service managed by systemd. See the following attachments for the configuration files:
[/etc/nginx/conf.d/netbox.is.depaul.edu.conf](https://github.com/digitalocean/netbox/files/1132495/nginx_configuration.txt)
[/etc/uwsgi.d/netbox.ini](https://github.com/digitalocean/netbox/files/1132498/uwsgi_configuration.txt)
[/etc/systemd/system/uwsgi-app@.socket](https://github.com/digitalocean/netbox/files/1132503/systemd_socket.txt)
[/etc/systemd/system/uwsgi-app@.service](https://github.com/digitalocean/netbox/files/1132504/systemd_service.txt)

The Netbox application uses a virtualenv to manage the packages locally. I know Python 3.4 is not  a release that you build against, but it is the only version available through the EPEL repo.

**Comment by jeremystretch** [comment] 2017-07-10 13:29
Duplicate of #1319. Will be fixed in v2.0.9.

**Closed by jeremystretch** 2017-07-10 13:29 UTC
