### ISSUE TITLE
Custom Field Selection: Multiple Selection

### ISSUE THREAD

**Issue by njgarfield** [digitalocean/netbox#3166] opened 2019-05-08 09:46 UTC
### Environment
* Python version:  3.6
* NetBox version:  2.5.12

### Proposed Functionality
This is a request to choose multiple entries from a custom select list similar to an HTML tag. Currently only possible to select a single entry from custom field select list in the Netbox UI. To describe the request another way - it is not possible to select multiple entries from a custom select list.

### Use Case
Site or router prefix advertisement, AKA routing policy, is often complex to describe and does not map nicely onto IP and DCIM schemas.
To document the intended members of a prefix list associated with a route map or policy map associated with a particular site or router it would be useful to be able to select multiple entries for a pre-defined list. There are other ways to work around this, such as packing information into a single text field, but it would be so much nicer in a multiple select list.

The ultimate use case is to dynamically compile prefix lists and configure routers with said list. The information can also be used for documenting intended advertisements to be checked with route monitoring systems.

### Database Changes
Perhaps. not sure.

### External Dependencies
None.

**Comment by jeremystretch** [comment] 2019-05-08 18:49
Duplicate of #2522

**Closed by jeremystretch** 2019-05-08 18:49 UTC
