### ISSUE TITLE
Assigning IP to Interface from Edit IP

### ISSUE THREAD

**Issue by aarjbdea** [digitalocean/netbox#1891] opened 2018-02-16 11:51 UTC
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

* Python version:  3.4.5
* NetBox version:  2.3.0-dev

### Description
When creating an IP or editing an IP that is not assigned to a device/interface, i propose that you should be able to assign this IP to a device/interface from the edit IP page. This would help when assigning out a number of new IP's to devices as at the moment i have to find out my free IP addresses and create them within netbox, note them down from netbox and then go to the interface that i want to assign the IP to and click assign IP and then do a search. It would speed up this process if this could all be done when creating/editing an IP. 

Not sure on the database or third party libraries

**Comment by jeremystretch** [comment] 2018-02-21 15:19
Duplicate of #1710

**Closed by jeremystretch** 2018-02-21 15:19 UTC

**Comment by aarjbdea** [comment] 2018-02-21 15:32
Okay, I get the comment about why this approach was taken, but does this not create more effort than required in some cases, for example, we set of a script to import all the devices for a new platform with all the interfaces added in bulk, we then go into the prefixes and see which IP's are free and then would assign these to a VM/device interface. doing it the other way round is okay in some cases but means you  would have to go into the prefixes first anyway to note down the free IP's and then create the IP's and then go back to each device and assign the IP to them (or create) whereas if it worked a little bit like when attaching a interface to another interface where it could be done either way i feel that it would improve efficiency when using netbox.
