### ISSUE TITLE
IP Adresses, add a hostname field

### ISSUE THREAD

**Issue by filiperegis** [digitalocean/netbox#335] opened 2016-07-19 18:53 UTC
Hi,

Is it possible to add a hostname field to IP Addresses?
There is a description field that we could use this way, but we're migrating from GestioIP and have information on both fields (hostname and description). Choosing one would be losing another.

Best Regards,
Filipe.

**Comment by fone** [comment] 2016-07-19 19:24
I'm also hoping this gets added soon. also coming from GestioIP

**Comment by jeremystretch** [comment] 2016-07-19 19:34
Duplicate of #166.

**Closed by jeremystretch** 2016-07-19 19:34 UTC
Labels: duplicate
