### ISSUE TITLE
New form factor interface types

### ISSUE THREAD

**Issue by alarido** [digitalocean/netbox#365] opened 2016-07-22 10:00 UTC
Hello,

It would be nice to have Coaxial and a way to differentiate fiber type, single-mode and multi-mode.

Thanks in advance.

**Comment by jeremystretch** [comment] 2016-07-22 13:05
Duplicate of #361. Please search for existing issues before creating a new one.

**Closed by jeremystretch** 2016-07-22 13:05 UTC
Labels: duplicate

**Comment by alarido** [comment] 2016-07-22 16:19
I did, but none of this words showed any matches:
coaxial
smc
sma
tmc
...

Also I tried without acronym (that was my mistake) single and multi mode, also without matches:
single-mode
multi-mode
