### ISSUE TITLE
site/room/rack overview

### ISSUE THREAD

**Issue by Armadill0** [digitalocean/netbox#671] opened 2016-11-08 12:18 UTC
It would be very handy if you could add some sort of overview about the rows and racks of a specific site. Maybe also a sub level like a room between a site and rack groups would be great to manage different rooms in a single data center.
The feature would be useful e.g. to plan cabling betweens racks, rows and so on.

**Comment by xenuser** [comment] 2016-11-08 12:36
I highly second this. NetBox as a DCIM solution is there to give you an overview of what you have: You have n amount of servers, you have n switches and routers and firewalls and so forth. Maintaining this data within NetBox gives you an overview of your IT landscape - why not doing such a thing for your racks by creating a feature which draws some sort of "map" of a room with all the rack rows?


And if you think this further, it might also make sense to link your room to a building within a site.
This certainly would add more layers of abstractions and hierarchy, but it would help to be more specific when describing sites, rack rooms etc.

**Comment by jeremystretch** [comment] 2016-11-08 14:33
> It would be very handy if you could add some sort of overview about the rows and racks of a specific site.

This is too vague to be actionable as a feature request. Please elaborate.

> Maybe also a sub level like a room between a site and rack groups would be great to manage different rooms in a single data center.

I think the model we have now strikes a good balance. The hierarchy goes site -> rack group -> rack, where the context of a rack group is up to the user to define. (Also, #164 has been opened to add the concept of a region containing multiple sites.) We want to avoid the hierarchy getting too top-heavy.

**Comment by nr-syscse** [comment] 2016-11-09 16:57
Maybe a top down view of your server room similar to the front/rear view of the racks. Sort of like a map for your server room.

**Comment by xenuser** [comment] 2016-11-09 17:05
A top down view of all racks is exactly what I have in mind, I guess it might be the same for Armadill0.

**Comment by drybjed** [comment] 2016-11-09 17:17
[OpenDCIM](http://opendcim.org/) has [a similar functionality](http://opendcim.org/screenshots.html).

**Comment by Armadill0** [comment] 2016-11-09 17:23
A top down view is exactly what I had in mind. 👍

**Comment by jeremystretch** [comment] 2016-11-09 19:52
Marking this as a duplicate of #114 then.

**Closed by jeremystretch** 2016-11-09 19:52 UTC
