### ISSUE TITLE
Recording PAT

### ISSUE THREAD

**Issue by DevilWAH** [digitalocean/netbox#2032] opened 2018-04-16 21:39 UTC
### Issue type
[ X ] Feature request 
[ ] Bug report      
[ ] Documentation   

Under an IP address you can only add one NAT IP, but for those of us using PAT we may have one public IP pointing at multiple internal IP based on port. Would it be possible to allow people to add multiple NAT translations for a single external IP? 

ie

77.205.168.25 NAT on port 443 to 192.168.10.10
77.205.168.25 NAT on port 22 to 192.168.200.50
77.205.168.25 NAT on port 389 to 192.168.110.78

### Description

**Comment by jeremystretch** [comment] 2018-04-18 15:50
Duplicate of #788

**Closed by jeremystretch** 2018-04-18 15:50 UTC
