### ISSUE TITLE
Device and Rack

### ISSUE THREAD

**Issue by andreas1o** [digitalocean/netbox#378] opened 2016-07-25 06:55 UTC
Would it be possible to not have rack position on a site as mandatory when you add a device to a site ? 

usecase.

We want to see if we can use this great system as a documentation system for sites and equipment where no actual racks exists. 

I know you could create a dummy rack that you place in the site, but it would be easier if you could skip that part.

**Comment by jeremystretch** [comment] 2016-07-25 13:49
Duplicate of #198

**Closed by jeremystretch** 2016-07-25 13:49 UTC
