### ISSUE TITLE
When adding a new site not all tenants are shown in the tenancy drop down

### ISSUE THREAD

**Issue by sschwetz** [digitalocean/netbox#1240] opened 2017-05-31 23:38 UTC
Issue type: When adding a new site not all tenants are shown in the tenancy drop down

Python version: 2.3
NetBox version: 2.0.4

After upgrade from 1.9.6 to 2.0.4 when adding a site only a partial set of tenants is shown in the tenant drop down.

If you would like screenshots I can supply them to an email address, they have customer data in them, so I am unable to share here.

**Comment by jeremystretch** [comment] 2017-05-31 23:51
Please enumerate the steps necessary to reproduce this behavior, including the creation of tenants that are not displayed.

**Comment by sschwetz** [comment] 2017-06-01 07:29
The tenants were pre-existing pre upgrade. The best way is probably with images

Here you can see there are 48 tenants
![total_tenants](https://cloud.githubusercontent.com/assets/19428602/26668846/e0faca0e-46ee-11e7-95c8-f774cf991051.PNG)

But when attempting to add a site the the tenants, Only a subset is shown
![shown tenants](https://cloud.githubusercontent.com/assets/19428602/26669066/c7535d2c-46ef-11e7-8cc9-15ecea1460cb.png)

**Comment by jeremystretch** [comment] 2017-06-01 12:56
Are the other tenants assigned to a tenant group? Only tenants not assigned to a group are shown initially. To display other tenants, first select the desired tenant group from the dropdown.

**Comment by sschwetz** [comment] 2017-06-01 13:56
I have checked that, no tenant have been assigned to groups.

**Comment by jeremystretch** [comment] 2017-06-01 15:16
I just created 50 tenants on a dev instance and they all appear as expected. Can you differentiate at all between the tenants which appear and those which do not?

Also, your Python version (2.3) is very outdated. Please upgrade to Python 2.7.

**Comment by jeremystretch** [comment] 2017-06-09 15:08
Closing due to lack of activity.

**Closed by jeremystretch** 2017-06-09 15:08 UTC
Labels: awaiting reply
