### ISSUE TITLE
API POST request tries to change 'form_factor' of interface without the change being in JSON

### ISSUE THREAD

**Issue by pm17788** [digitalocean/netbox#2405] opened 2018-08-31 14:10 UTC
### Environment
* Python version:  3.5.2
* NetBox version:  2.4.4

### Steps to Reproduce
PATCH with `{"description":"Some string there"}`

### Expected Behavior
PATCH request to succeed.

### Observed Behavior
Error is output about trying to change the `form_factor` of the NIC in question. 
```
curl -X GET "https://netbox.DOMAIN/api/dcim/interfaces/6936984/" -H  "accept: application/json" -H  "X-CSRFToken: <SANITIZED>"
{
  "id": 6936984,
  "device": {
    "id": 392724,
    "url": "https://netbox.DOMAIN/api/dcim/devices/392724/",
    "name": "server892",
    "display_name": "server892"
  },
  "name": "bond0",
  "form_factor": {
    "value": 1200,
    "label": "SFP+ (10GE)"
  },
  "enabled": true,
  "lag": null,
  "mtu": 1,
  "mac_address": null,
  "mgmt_only": false,
  "description": "Interface 'bond0' on host 'server892'",
  "is_connected": false,
  "interface_connection": null,
  "circuit_termination": null,
  "mode": null,
  "untagged_vlan": null,
  "tagged_vlans": [],
  "tags": []
}

curl -X PATCH "https://netbox.DOMAIN/api/dcim/interfaces/6936984/" -H  "accept: application/json" -H  "Content-Type: application/json" -H  "X-CSRFToken: <SANITIZED>" -d "{\"description\": \"Interface 'bond0' on host 'server892'\"}"
{
  "non_field_errors": [
    "Cannot change interface form factor; it has LAG members (eth0, eth1)."
  ]
}
```

**Comment by pm17788** [comment] 2018-09-04 13:32
@lampwins: Good call. When I change the NIC's `form_factor` to LAG, the LAG memebers show up.

The only data manipulation we do is via the API or the WebUI. However, part of the upgrade procedure (this installation started life from NetBox 2.2.7 and has been incrementally upgraded as updates came out) does do things with SQL, so I cannot help but wonder if I somehow caused the upgrade process make this change?

**Comment by pm17788** [comment] 2018-09-04 15:11
I *suspect* that this is related to #2391

**Comment by pm17788** [comment] 2018-09-05 12:38
@lampwins: To me, it seems wrong that I'm getting what appears to be an uncommanded change request - the JSON doesn't contain a `form_factor` change.

**Comment by jeremystretch** [comment] 2018-09-05 13:17
You're getting the error because the object is failing validation when saving. Remove the LAG member assignments and it will work. The root cause is that LAG members have somehow been assigned to a non-LAG interface. This would require a new bug to address, but please open one _only_ if you can provide the exact steps someone else can take to recreate the issue.

**Closed by jeremystretch** 2018-09-05 13:17 UTC
Labels: status: gathering feedback
