### ISSUE TITLE
Mapping of cable connections

### ISSUE THREAD

**Issue by tormodhope** [digitalocean/netbox#882] opened 2017-02-08 10:03 UTC
Like the Link Management plugin for Racktables does.
That is a great enhancement for racktables, and will be for Netbox as well.

**Comment by tioan** [comment] 2017-02-08 14:49
I think this is an duplicate of #20

**Comment by jeremystretch** [comment] 2017-02-08 14:55
Yep, #20 is pretty much a catch-all for everything related to cable plant mapping.

**Closed by jeremystretch** 2017-02-08 14:55 UTC
