### ISSUE TITLE
Enhancement-Auto generate IP addresses based on the entered Prefix

### ISSUE THREAD

**Issue by aveloz** [digitalocean/netbox#706] opened 2016-11-26 14:01 UTC
After adding a Prefix, we need to create the IP address for that prefix manually. It would be great if the system can auto generate those IP's.

For example adding the prefix 192.168.0.0/24...In the IP address tab add a button to generate all of the IP's of that prefix. #

**Comment by jeremystretch** [comment] 2016-11-28 14:35
Duplicate of #181

**Closed by jeremystretch** 2016-11-28 14:35 UTC
