### ISSUE TITLE
Adding host devices to a cluster should exclude devices already assigned

### ISSUE THREAD

**Issue by Gelob** [digitalocean/netbox#1579] opened 2017-10-12 21:52 UTC
### Issue type
[ ] Feature request 
[ X ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.5
* NetBox version:  2.2.1

### Description
When searching for devices to add to a virtualization cluster (virtualization/clusters/1/devices/add/), devices that are already part of a cluster show up. If you attempt to add a device that is already part of an existing cluster you will get a Server Error `<type 'exceptions.TypeError'>

'NoneType' object is not iterable`

This would also help in finding devices quicker because the search only returns a limited number of results.

**Comment by RyanBreaker** [comment] 2017-10-12 21:55
I'll take a stab at this, hold my beer.

This should also probably be a bug report instead of feature request, especially since it does return an error.

**Comment by Gelob** [comment] 2017-10-12 21:57
@RyanBreaker consider your beer held. I've updated it to a bug report. I couldn't decide and figured feature.

**Comment by jeremystretch** [comment] 2017-10-13 19:05
@Gelob I'm not able to reproduce this. Could you please update your report with the steps needed to reproduce the error?

**Comment by RyanBreaker** [comment] 2017-10-13 20:15
I was actually about to say, I don't get any Python errors but instead just a more generic message saying it cannot be added.

**Comment by RyanBreaker** [comment] 2017-10-14 20:22
@jeremystretch I guess it comes down to how we want it to behave then, if we want to just make devices already in a cluster even show up or just disable them from being selectable.

**Comment by Gelob** [comment] 2017-10-16 21:32
I think it has to do with when the cluster is assigned to a site, if its not assigned to a site I just get "Select a valid choice. 1812 is not one of the available choices."

If I assign the cluster to a site I do get the attached error
![screen shot 2017-10-16 at 4 29 04 pm](https://user-images.githubusercontent.com/422752/31636291-6c9536e2-b28f-11e7-9f5e-76f4f1356574.png)

1. Create a new cluster, and assign it to a site.
2. Create a new device in that same site
3. Assign that device to the new cluster you created
4. Try to assign that same device to that cluster (or another cluster that has a site assignment)

**Comment by jeremystretch** [comment] 2017-10-17 14:02
Fixed in 34f1a9ebfb6faa4c98fb6792fb3994a18f860990

**Closed by jeremystretch** 2017-10-17 14:02 UTC
Labels: bug
