### ISSUE TITLE
"Create and Add Another" - keep previous formular data 

### ISSUE THREAD

**Issue by Armadill0** [digitalocean/netbox#328] opened 2016-07-19 07:08 UTC
If you currently add a new device, rach or whatever, it is possible to submit it via the "Create" or "Create and Add Aanother" buttons.
It would be very handy if the latter method would keep the formular data which has been entered by the user, to speed up entering multiple devices of the same type.

**Comment by bellwood** [comment] 2016-07-19 15:29
Dupe of #225

**Closed** 2016-07-19 17:12 UTC
Labels: duplicate
