### ISSUE TITLE
Add custom fields to interface model/interface view

### ISSUE THREAD

**Issue by kmiller7851** [digitalocean/netbox#2281] opened 2018-07-28 04:12 UTC
# Issue type
[ x ] Feature request 
[ ] Bug report 
[ ] Documentation 
[ ] Housekeeping

# Environment
* Python version: 3.6
* NetBox version: 2.4-beta1
# Description
With the new interface view, and interface models seemingly being moved to a primary model (as defined here:
https://github.com/digitalocean/netbox/wiki/Frequently-Asked-Questions#can-we-add-custom-fields-to-more-models ), I would love to see custom fields added to them. There is definitely a need to track infomation that doesn't quite fit anywhere else, such as niche interface features like QinQ (or documenting any pop/push/swap operations), interface families(mpls, vpls, ccc, iso,pppoe, etc), and so on.

As always, thanks for the work on this, project, it has definitely made my life easier!

**Comment by jeremystretch** [comment] 2018-07-30 13:05
Duplicate of #1254

**Closed by jeremystretch** 2018-07-30 13:05 UTC
