### ISSUE TITLE
Rack devices ordering drag and drop support?

### ISSUE THREAD

**Issue by ksuuk** [digitalocean/netbox#1996] opened 2018-03-28 06:21 UTC
Issue type:

[x] Feature request
[ ] Bug report
[ ] Documentation

Environment:

Python version: 2.7.5
NetBox version: 2.3.2

Description:

Rack devices add & edit. Please add rack devices ordering drag and drop ajax support.

**Comment by jeremystretch** [comment] 2018-03-29 14:04
Duplicate of #124. This won't be revived any time soon as we have a huge backlog of more pressing features to implement.

**Closed by jeremystretch** 2018-03-29 14:04 UTC
