### ISSUE TITLE
[feature-request] add a map of the DC / Room

### ISSUE THREAD

**Issue by lodpp** [digitalocean/netbox#499] opened 2016-08-23 07:25 UTC
Hello,

Is it planned to add a map of the datacenter and room inside netbox?
Smth like that for the room: http://www.squaremilesystems.com/wordpress/wp-content/uploads/2012/03/Floorplan-final1.png

For the dc, well just how to room are located in the DC / floor

The goal is to have a quick view of rooms with basic information ( dimension/height/power avail) without the need to go on each rack 

Thanks and Regards,

**Comment by jeremystretch** [comment] 2016-08-23 13:23
Duplicate of #114

**Closed by jeremystretch** 2016-08-23 13:23 UTC
