### ISSUE TITLE
Relax the rack naming constraint with rackgroups

### ISSUE THREAD

**Issue by Zanthras** [digitalocean/netbox#643] opened 2016-10-26 17:05 UTC
I think it would make sense to alter the rack naming constraint to include the rack groups instead of just the site.

Take for instance a Site thats a single building, but within it it has multiple floors with multiple IDF's per floor. Each IDF is its own rack group, but within each IDF the racks can easily be named quite identically, the idf (rack group) is the unique identifier.

With the current constraints the rack names basically have to include the rack group identifier, kinda making it redundant.

**Comment by jeremystretch** [comment] 2016-10-26 17:28
Duplicate of #238

**Closed by jeremystretch** 2016-10-26 17:28 UTC
Labels: duplicate
