### ISSUE TITLE
Add new Feature.

### ISSUE THREAD

**Issue by Darkbcn** [digitalocean/netbox#1518] opened 2017-09-20 12:13 UTC
### Issue type
[X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment

* NetBox version:  Future version

### Description

Sometimes we have a switch, on this switch we have the ports and on this ports maybe we have configure a VLAN ID or VLAN ID's and Tagged or Untagged.

For example

Port 0/15

VLAN_ID 100 Tagged
VLAN_ID 101 Untagged
VLAN_ID 200 Tagged
VLAN_ID 300 Tagged

we can check the best way to view the configuation for a switch.

Maybe we need to add a new table to the database for this information

Switch_1
-------------------------------------------------------------------------
| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 |
-------------------------------------------------------------------------
  |
  |__ VLAN_ID |  Status |  Name_VLAN
         100              T             PRODUCTION
         101              U             MANAGEMENT
         200              T             STATUS
         300              T             SCSI

Attached a file with an example
[switch_example.xlsx](https://github.com/digitalocean/netbox/files/1317674/switch_example.xlsx)

**Comment by jeremystretch** [comment] 2017-09-20 13:13
Duplicate of #150

**Closed by jeremystretch** 2017-09-20 13:13 UTC

**Comment by Darkbcn** [comment] 2017-09-20 14:01
Hi jeremystretch,

this option is for view the configuration of the switch and add a new option to menu.

the idea is view similar as excel but included on netbox.

and check if a port is used from other option.

**Comment by Darkbcn** [comment] 2017-09-20 14:02
please reconsider re-open feature.

**Comment by LBegnaud** [comment] 2017-09-20 14:17
He closed it because it's a duplicate, look at the linked issue to track it
