### ISSUE TITLE
Direct access to services information in GUI?

### ISSUE THREAD

**Issue by ksuuk** [digitalocean/netbox#1962] opened 2018-03-09 14:36 UTC
Issue type

[x] Feature request
[ ] Bug report
[ ] Documentation

Environment

Python version: 2.7.5
NetBox version: 2.3.1

Description:

Right now in GUI, services accessible true "Devices" menu, but in API services are under "IPAM" path. Please add direct access to services into GUI, under "IPAM" menu.

**Comment by jeremystretch** [comment] 2018-03-09 19:49
Duplicate of #1673

**Closed by jeremystretch** 2018-03-09 19:49 UTC
