### ISSUE TITLE
Custom Webhooks

### ISSUE THREAD

**Issue by esapozhnikov** [digitalocean/netbox#2771] opened 2019-01-11 00:45 UTC
### Environment
* Python version:  3.5.4
* NetBox version:  2.5.1

### Proposed Functionality

Allow customization of the Webhooks payload

Example:
`curl -X POST \
     -F token=TOKEN \
     -F "ref=REF_NAME" \
     -F "variables[RUN_NIGHTLY_BUILD]=true" \
     https://gitlab.domain.com/api/v4/projects/123/trigger/pipeline`

### Use Case
This would allow changes to data in NetBox to trigger Gitlab pipelines that can request data from NetBox and process it as needed.

**Comment by jeremystretch** [comment] 2019-01-11 02:08
Duplicate of #2651

**Closed by jeremystretch** 2019-01-11 02:08 UTC
