### ISSUE TITLE
Feature: Tenant/Site Template

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#812] opened 2017-01-18 13:03 UTC
It would be helpful to be able to use a template when creating a Tenant or Site which could include default information with the ability to populate fields using the Tenant name/slug. 

An example would be if you wanted to create a new Tenant which had specific information to be included in the comments field or a custom field which would be automatically populated from the Tenant name.

As Netbox is normally implemented in conjunction with other supporting systems such as helpdesks, billing, portals etc, linking them together for quick reference would help point someone to the correct location based on the name/code/id/reference. 

Another option is a custom field template which could use the Tenant name/slug or even a Tenant code/id/reference field.

Example: 
URL: smb://1.1.1.1/folder/[name]
URL: https://1.1.1.1/customer/[name]

**Comment by jeremystretch** [comment] 2017-01-23 14:50
This seems like it may be covered by #600. Please read through the discussion there and let me know. If so, I'll mark this as a duplicate of that issue.

**Comment by InsaneSplash** [comment] 2017-01-24 05:50
It seems very close to what I was proposing. Would really make life easier if one good use the variables in custom fields as a start! Thanks

**Comment by jeremystretch** [comment] 2017-01-24 14:25
Marking as a duplicate of #600 for reference

**Closed by jeremystretch** 2017-01-24 14:25 UTC
Labels: duplicate
