### ISSUE TITLE
Regional Grouping of Sites

### ISSUE THREAD

**Issue by martink2** [digitalocean/netbox#617] opened 2016-10-14 08:30 UTC
### Current State 

Currently we have the Site Object which references a physical DC location
with Address etc. For some objects like VLAN's we have a mandatory site 
relationship, for others it is optional like IP Prefixes. Once the Site attribute is set 
on an object i can only use it in that site.

### Problem

We are managing a large number of DC Sites, some of them don't have any relationship with
each other fitting the current implementation very well. But we also have a larger number of DC's
which are  located in the same metro area. Those have different buildings and addresses, so for the rack locations etc they are very much different sites but since they are closely interconnected from the network side they are more behaving like one (Vlans are Spanning Sites, so are IP Networks). So currently I have double the VLAN's and I cant assign Subnets to them since once 
assigned I can no longer use it on both sides.

### Proposal

Proposal is to implement a new object which represents a cluster of Sites (I would call it a region)
which are different physical locations (For Racks / Groups / Equipment ) but behave like one entity in regards to networking objects (VLAN, Subnets etc.).
For all objects that can currently be assigned or have to be assigned to a site the logic would be to assign them either to a site or a region making it available in all sites of the region.

Region 1 = Site A, Site B
VLAN 100 = Region 1
Prefix 10.0.0.0/24 Wtih Vlan 100 

--> Results in I can use the Prefix in Site A and B like i could now with a prefix assigned directly to the site.

**Comment by jeremystretch** [comment] 2016-10-14 13:16
Duplicate of #164

**Closed by jeremystretch** 2016-10-14 13:16 UTC
