### ISSUE TITLE
Export Rack Elevations view

### ISSUE THREAD

**Issue by slarimore02** [digitalocean/netbox#1270] opened 2017-06-14 15:53 UTC
Feature Request 

Would like to request the ability to export the Rack Elevations view to PDF or possibly other formats. Most teams need to provide lab teams with Rack Elevations and having the ability to export the Netbox view and provide it to them would be a valuable addition.

**Comment by jeremystretch** [comment] 2017-06-14 16:32
Going to mark this as a duplicate of #160 since I'm pretty sure this is how that one will turn out.

**Closed by jeremystretch** 2017-06-14 16:32 UTC
