### ISSUE TITLE
Cable ID for Interconnections

### ISSUE THREAD

**Issue by tvberlin** [digitalocean/netbox#1291] opened 2017-06-21 12:18 UTC
### Issue type:

Feature Request

**NetBox version:** v2.0.3

We're tagging each cable between devices with a unique ID (numbers only) and would love to have a corresponding field available in the "Connect Interfaces" dialog. This ID should be visible in the interface list of the inter-connected devices.

Thanks for your awesome work! :-)

Theo Voss
ANEXIA

**Comment by jeremystretch** [comment] 2017-06-21 13:47
This is a duplicate of #589. Cable IDs will be included as part of #20; please see [this comment](https://github.com/digitalocean/netbox/issues/923#issuecomment-283049890) for more background.

**Closed by jeremystretch** 2017-06-21 13:47 UTC
