### ISSUE TITLE
bug: Global Search: Tenant no hyperlink

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#1193] opened 2017-05-17 13:26 UTC
When viewing the results of a global search, the tenant contains no hyper-link.

**Comment by jeremystretch** [comment] 2017-05-17 13:49
Duplicate of #1160.

(In the future, please be sure to utilize the bug report template.)

**Closed by jeremystretch** 2017-05-17 13:49 UTC

**Comment by InsaneSplash** [comment] 2017-05-17 14:00
Will do thanks.
