### ISSUE TITLE
Bug: VRF and IP Prefixes menu

### ISSUE THREAD

**Issue by aveloz** [digitalocean/netbox#709] opened 2016-11-26 15:29 UTC
After clicking on an IP Prefix from the VRF view.

When you want to go back to the VRF clicking on the ribbon menu, the VRF menu links to:

http://netbox.localdomain/ipam/prefixes/?vrf=1 instead of http://netbox.localdomain/ipam/vrfs/1/

**Comment by jeremystretch** [comment] 2016-11-28 14:37
Duplicate of #696

**Closed by jeremystretch** 2016-11-28 14:37 UTC
