### ISSUE TITLE
Prepopulate forms with tenant field where applicable

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#858] opened 2017-01-31 09:05 UTC
1. When adding a new site to a tenant, after selecting the sites option within the tenant, it would be helpful to auto-select the tenant within which the site is being attached to. Currently the add site is treated as an independent process even though its called from within the Tenants workflow.

2. When adding a new device to a site, one is still required to choose the tenant and the site even though the request to add a new device was accessed from the site itself which in turn is linked to a tenant. This can also cause mistakes to be made by linking a device to an incorrect tenant/site.

As the system grows with 1000's of sites/tenants, searching for the correct site starts to become unmanageable.

**Comment by jeremystretch** [comment] 2017-04-19 18:53
Seems to be a duplicate of #446

**Closed by jeremystretch** 2017-04-19 18:53 UTC
Labels: enhancement
