### ISSUE TITLE
Add stacking interfaces for stackable switches

### ISSUE THREAD

**Issue by sschwetz** [digitalocean/netbox#326] opened 2016-07-19 01:45 UTC
Is it possible to add a switchport type of "stacking" to allow network diagrams etc to show when switches are stacked in the topography. I have currently just added the module ports as network ports, and linked them as 1gb ethernet, but they are really stacking cables. It all works, it just doesn't site nice with my OCD ;-)

I have to do it this way, as the stacked switches are in separate racks.

**Comment by jeremystretch** [comment] 2016-07-19 13:23
What type of cabling/port do these use? E.g. what should we call it in the list of interface types?

**Comment by ryanmerolle** [comment] 2016-07-19 13:39
Cisco calls them StackWise & StackWise Plus ports.  Juniper calls them Virtual Chassis Ports.

Looking through IOS devices that are stacked, I see no special port labels, just switch status and # of the member in the stack.  I am pretty sure only stack cable ports can be used here.

In JUNOS I see port labeling like vcp-1/3/0.  With some JUNOS platforms a special VC port can be used or any regular port can be used.

- [JUNOS show virtual chassis status](http://www.juniper.net/documentation/en_US/junos15.1/topics/reference/command-summary/show-virtual-chassis-status-mx-series.html)
- [JUNOS EX4200/4500 VC Planning](http://www.juniper.net/documentation/en_US/release-independent/junos/topics/reference/requirements/virtual-chassis-ex4200-ex4500-hardware-planning.html)
- [JUNOS VC Config](http://www.juniper.net/documentation/en_US/junos16.1/topics/task/configuration/virtual-chassis-ex4200-uplink-vcp-cli.html)
- [Cisco Catalyst 3750 Series Stacks](http://www.cisco.com/c/en/us/products/collateral/switches/catalyst-3750-series-switches/prod_white_paper09186a00801b096a.html)

**Comment by jeremystretch** [comment] 2016-07-19 13:48
Is it worth enumerating the various types of proprietary stacking interfaces? Should we just define a "stacking" or "virtual chassis" interface type?

**Comment by cstueckrath** [comment] 2016-07-19 14:14
IBM/Lenovo Bladecenter switches are usually stacked by a bonded 2x 10G DAC-Cable or SFP+

**Comment by jeremystretch** [comment] 2016-07-19 14:20
Similarly, Juniper EX4300s use normal QSFP+ interfaces. In those cases I'd suggest people just use the existing interface types.

**Comment by ryanmerolle** [comment] 2016-07-19 14:36
Yea I would agree with @jeremystretch.

Would a custom port attribute help to identify it as a stack/VC port?  This could be addressed by custom fields #129. If it was not a custom attribute, then it would be more obvious to users and prevent these future requests, but a field would meet this need to identify this special port.

**Comment by jeremystretch** [comment] 2016-07-19 14:44
> Would a custom port attribute help to identify it as a stack/VC port?

We need to define at least one interface type to cover the proprietary types. It could be a generic "Stacking" type (similar to the existing "Virtual" type) or we could create one for each physical specifiction (e.g. "Cisco StackWise," "Cisco StackWise Plus," etc.).

**Comment by ryanmerolle** [comment] 2016-07-19 21:00
That'e fine with me.  I did not figure you wanted to support that given potential creep towards cluster/stack support requests on the nodes/devices themselves.

Can you also add a POE type also?

**Comment by sschwetz** [comment] 2016-07-20 06:21
On HP Procurves they are called "Stacking Ports" and they are modules in seperate cards. 
HP Comware they are bonded SPF+ or QSPF+ Ports

**Comment by peelman** [comment] 2016-07-22 17:14
duplicate of #99

**Comment by jeremystretch** [comment] 2016-07-22 17:27
This is just for adding one or more new interface form factors for "stacking" ports. #99 deals with treating multiple devices as a single logical entity.

**Comment by jeremystretch** [comment] 2016-07-28 17:56
Folding this into #167 as part of a larger initiative to add more interface form factors.

**Closed by jeremystretch** 2016-07-28 17:56 UTC
Labels: improvement
