### ISSUE TITLE
Add ability to import interfaces

### ISSUE THREAD

**Issue by edchiodo** [digitalocean/netbox#890] opened 2017-02-09 00:00 UTC
When creating interfaces en mass (for example, adding bond0.xx virtual interfaces for a substantial number of hosts) the process is very time consuming.

Would it be possible to add an "Import Interfaces" feature, with the following fields:

- Parent Device
- Interface Name
- Form Factor
- MAC
- Description

Much obliged!

**Comment by jeremystretch** [comment] 2017-02-09 00:23
Duplicate of #822

**Closed** 2017-02-09 00:24 UTC
Labels: duplicate
