### ISSUE TITLE
Support comment field in device types

### ISSUE THREAD

**Issue by drybjed** [digitalocean/netbox#638] opened 2016-10-26 09:08 UTC
Currently comments can be added to individual devices, but not to the device types. Adding this field as for example, "Device type comments" would allow entering common information about particular devices, like URLs to product and support pages, general information about the manufacturer, quirks of a particular set of devices worth membering, etc.

**Comment by jeremystretch** [comment] 2016-10-26 13:01
Duplicate of #122

**Closed by jeremystretch** 2016-10-26 13:01 UTC
