### ISSUE TITLE
Editing Device Type interfaces causes issue with pre-created devices

### ISSUE THREAD

**Issue by DavidAkroyd** [digitalocean/netbox#2343] opened 2018-08-09 11:12 UTC
### Environment
* Python version:  3.5.2
* NetBox version:  2.4.1 upgraded to 2.4.2

### Steps to Reproduce
Create a new Device type without Network interfaces
Create a device in that device type
Add network interfaces to device
Add network interfaces to device type
("Update" device to device-type)

### Expected Behavior
Devices would add new interfaces for device type

### Observed Behavior
Device does not receive new interfaces

Additionally, can no longer delete the device receiving error message:
`<class 'dcim.models.DoesNotExist'>
Device matching query does not exist.`

To solve, must delete interfaces from created device, and then can delete the device

**Comment by jeremystretch** [comment] 2018-08-09 13:12
> Device does not receive new interfaces

This is desired behavior as explained in [the documentation](http://netbox.readthedocs.io/en/stable/core-functionality/devices/).

> Additionally, can no longer delete the device receiving error message:

I'm not able to replicate this following the steps you posted above. Please post the _exact_ steps someone else can take to reproduce the bug, beginning with the creation of a new device type.

**Comment by DavidAkroyd** [comment] 2018-08-09 14:12
The steps I took were in 2.4.1

I created a Device type (Machine) with no network interfaces
I created multiple devices of this type (Mac1)
I added a network interface (Intel) to Mac1 and added an IP address and connection
I added network interfaces to the device type
I bulk changed devices Mac1-50 to include a tenant and also selected the device type

I was then unable to delete the device (Mac1) which already had a network connection, receiving the error message as indicated above

However repeating the same steps in 2.4.2 directly no longer appears to cause the same issue, so I am unsure if this then was fixed as part of 2.4.2 indirectly. The issue appears to be related to https://github.com/digitalocean/netbox/issues/2323 though there is no mention of this being fixed also for non-virtual machines

**Comment by jeremystretch** [comment] 2018-08-09 14:51
Yep, looks like the same bug that was fixed in v2.4.2.

**Closed by jeremystretch** 2018-08-09 14:51 UTC
Labels: status: revisions needed
