### ISSUE TITLE
DCIM: Battery Backup

### ISSUE THREAD

**Issue by aveloz** [digitalocean/netbox#710] opened 2016-11-28 00:07 UTC
I have defined a device type named UPS3000...then I added a device named UPS-Rack1 and assigned that device type...within I defined 8 Power Outlets and 1 PowerPort...The issue here is there no way to define Power Circuits in order to assign it to a Device...in this case I can only assign the Power Ports to the Powers Outlets...

**Comment by jeremystretch** [comment] 2016-11-28 14:39
Duplicate of #54.

This is the fourth issue of yours that I've had to close as a duplicate. Please utilize the search function before opening new issues.

**Closed by jeremystretch** 2016-11-28 14:39 UTC

**Comment by aveloz** [comment] 2016-11-28 14:52
Sorry I think...
