### ISSUE TITLE
Tenant search does not return the correct results

### ISSUE THREAD

**Issue by superthing** [digitalocean/netbox#3160] opened 2019-05-06 19:52 UTC
Environment

    Python version: Python 3.5.2
    NetBox version: 2.5.8

Steps to Reproduce

1. Search Netbox for a tenants full name.
2. Observe no values returned.
3. Remove the tenants first/ last name.
4. Observe the correct results returned.

Expected Behavior

Searching a tenant by their full name returns the correct tenant in search results.

Observed Behavior

Searching by certain tenant's full names returns no search results. Searching by first / last name returns the correct search results (pictures attached). This has been observed on a small portion of tenant searches. We have 12120 Tenants.

![netboxs1](https://user-images.githubusercontent.com/4330944/57250746-056dc600-6ffd-11e9-9118-426c1fcb77c7.jpg)
![netboxs2](https://user-images.githubusercontent.com/4330944/57250755-0a327a00-6ffd-11e9-9608-007e48577fbd.jpg)
![netboxs3](https://user-images.githubusercontent.com/4330944/57250910-6d241100-6ffd-11e9-8e18-50a840f95cfe.jpg)

**Comment by DanSheps** [comment] 2019-05-06 21:07
I noticed you were a number of versions behind.  Please upgrade to the latest version of Netbox.

I will attempt to recreate this on the latest master.

**Comment by robbagithub** [comment] 2019-05-06 21:39
I've tested this and it's a problem in 2.5.4 which old as well I know. We've never hit this bug as no one ever bothers to type in full name!

**Comment by superthing** [comment] 2019-05-06 21:57
I have upgraded to 2.5.12 and am still experiencing the issue.

**Comment by DanSheps** [comment] 2019-05-06 22:50
Are all of these Tenants in a Tenant Group?

**Comment by DanSheps** [comment] 2019-05-06 23:43
I just loaded a Master pull from Netbox with 10K tenants, I am unable to reproduce this.

For now, this will be marked as invalid.  Otherwise, please provide proper steps to fully reproduce this.

**Comment by superthing** [comment] 2019-05-06 23:44
Yes, we have all of our Tenants in different Tenant Groups. The group that this Tenant is in has 10910 entries.

**Closed by DanSheps** 2019-05-06 23:43 UTC

**Comment by superthing** [comment] 2019-05-06 23:48
I understand that it is difficult to reproduce as I have not noticed a pattern with the Tenants that are causing problems. It is still an issue.

**Comment by DanSheps** [comment] 2019-05-06 23:56
If you can provide steps to reproduce the issue here: https://master.netbox.dansheps.com/ I can re-open the issue.

**Comment by superthing** [comment] 2019-05-07 00:20
Thanks for the help! I'll need to talk with my colleagues about moving forward with this issue.
