### ISSUE TITLE
Custom fields for services?

### ISSUE THREAD

**Issue by ksuuk** [digitalocean/netbox#1961] opened 2018-03-09 14:36 UTC
Issue type

[x] Feature request
[ ] Bug report
[ ] Documentation

Environment

Python version: 2.7.5
NetBox version: 2.3.1

Description

Please add custom fields to device > services, right now there is only one hard coded "Description" field, but we need more fields. And these custom fields should be included in overview https://github.com/digitalocean/netbox/issues/1673

P.S. What is the background of custom fields for some objects only? Is the existing selection made by real need or based by some logic or datamodel?

**Comment by jeremystretch** [comment] 2018-03-09 15:17
Duplicate of #1762

**Closed by jeremystretch** 2018-03-09 15:17 UTC
