### ISSUE TITLE
Request to add more virtual hdd on virtual machince Resource

### ISSUE THREAD

**Issue by sacy80** [digitalocean/netbox#1815] opened 2018-01-10 04:41 UTC
hi would like to request . is it possible to add more virtual hdd on virtual machince resources.

Thanks alot

**Comment by jeremystretch** [comment] 2018-01-10 04:54
Thank you for your interest in NetBox. We require that all issues be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!

**Comment by jeremystretch** [comment] 2018-01-10 14:16
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).

**Closed by jeremystretch** 2018-01-10 14:16 UTC
