### ISSUE TITLE
Add ability to customize columns

### ISSUE THREAD

**Issue by quantumknot** [digitalocean/netbox#791] opened 2017-01-11 11:44 UTC
Sorry if this is a duplicate of another inquiry. I did try to search to make sure this wasn't a duplicate...

Is it possible to customize columns in the various list views?  So for example if one clicks on devices|devices, the default columns are as follows:

Name		Tenant	Site	Rack	Role	Type	IP Address

It would be great if one could add/remove columns whether an existing or even from a custom field added to the form.  Also this would reflect in an export as well.

This is very useful for the ability to locate information quickly based on data in any of the particular columns, sort by, and as already mentioned exporting of these selected columns. 

Thank you in advance

**Comment by jeremystretch** [comment] 2017-01-11 14:20
Duplicate of #492

**Closed by jeremystretch** 2017-01-11 14:20 UTC
