### ISSUE TITLE
Existing IP cannot be assigned to Virtual Machine or Device

### ISSUE THREAD

**Issue by martink2** [digitalocean/netbox#1595] opened 2017-10-15 20:56 UTC
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.12
* NetBox version:  2.2.1

### Description
Existing IP's without a Device or VM assignment can't be assigned anymore.

When using the + Sign on the interface device the assignment is preset to the current device/vm.
Putting the already existing IP in as address results in the expected duplicate failure.
The edit form for existing IP's does not have an option to assign to a device / vm either.

Editing an already assigned IP gives the option to change the interface but not the device it is associated with.

**Comment by lae** [comment] 2017-10-16 08:51
I'm affected by this, too, but this seems like it would have been an intentional change...?

**Comment by InsaneSplash** [comment] 2017-10-16 09:28
I am also not able to assign an IP to an existing device as there is no option to select the device and interface. When you add an IP to an interface through a device it works fine.

**Comment by InsaneSplash** [comment] 2017-10-16 13:48
Help :)

Missing interface assignment:

![image](https://user-images.githubusercontent.com/16985649/31615294-6bef2a46-b289-11e7-9855-fd4c0cd525ab.png)

**Comment by jeremystretch** [comment] 2017-10-16 15:53
Duplicate of #1512

**Closed by jeremystretch** 2017-10-16 15:53 UTC
