### ISSUE TITLE
Add a depth field in rack properties

### ISSUE THREAD

**Issue by rdegez** [digitalocean/netbox#1763] opened 2017-12-11 18:01 UTC
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: N/A 
* NetBox version:  N/A 

### Description
Current racks properties include width & height fields.

Another important property for a rack is depth.

Could you please add a depth field (with a selector like for the width field I guess) ?
Common depth value are 800 (mm), 900 (mm), 1000 (mm) & 1200 (mm) (or their equivalent in imperial system of course ;-)

(Maybe maximum weight would be a nice addition as well ?)

Regards,

**Comment by jeremystretch** [comment] 2017-12-13 16:56
Duplicate of #450

**Closed by jeremystretch** 2017-12-13 16:56 UTC

**Comment by rdegez** [comment] 2017-12-13 20:30
Oops, should have searched in the issue backlog before... sorry :-o
