### ISSUE TITLE
Feature request: Global search box

### ISSUE THREAD

**Issue by nktl** [digitalocean/netbox#873] opened 2017-02-06 10:21 UTC
I think one of the the main benefits of having global assets database is to be able to instantly locate them, but at the moment using search functionality is a bit tedious: I need to know what exactly type/class (device, rack, circuit, device type, etc) the thing I am looking for belongs to and then I have to navigate to the very specific place where search for the particular class is possible (like Devices -> Device Type).

It would be amazing to have always visible, 'global' search box at the top of the page, please see my quick mockup:

![image](https://cloud.githubusercontent.com/assets/17342015/22642699/bf001de6-ec53-11e6-9fea-de30c2a4291a.png)

Possible use scenarios would be as follows:

1. I want to locate some particular Exchange server, but I don't exactly remember how is it called or where it is. In such case I can just type 'exch' in the globlal search box. This would match all the servers containing name 'exch', but additionally all device roles like 'Exchange Server' as well as VLANs, etc with the name containing 'exch' string  - which I can explore further to locate my box.

2. I just type serial number / asset tag (or part of it) of the device in global search box - and it instantly comes up with the pieces of equipment that match the pattern.

3. Same thing - I paste IP address there and it comes up with the matching subnet objects - as well as devices assigned with the particular address.

4. I want to locate all Cisco 3850 devices in the datacenter - I just type 3850 in the global search box, and it comes up with the 3850 device type + all the devices that belong to it.

Etc etc.

**Comment by candlerb** [comment] 2017-02-06 15:28
Strongly seconded.

When I am searching for a device I don't know if the text is in the description of an IP address object, or the name of a device, or the description of the interface.

**Comment by candlerb** [comment] 2017-02-06 15:50
Dupe of #159 ?

**Comment by jeremystretch** [comment] 2017-02-07 15:03
Yes, this is a duplicate of #159.

**Closed by jeremystretch** 2017-02-07 15:03 UTC
