### ISSUE TITLE
The UI for device interfaces cannot handle same slot number range with a different prefix

### ISSUE THREAD

**Issue by x-radeon** [digitalocean/netbox#780] opened 2017-01-05 22:46 UTC
When adding two different ranges of interfaces for a device, the UI doesn't like it when you use the same slot number even if the prefix is different, example:

Both of these added to single device
Fa0/[1-48]
Gi0/[1-4]

Will show as this:
        Gi0/1	100BASE-TX (10/100ME)
	Fa0/1	100BASE-TX (10/100ME)
	Gi0/2	100BASE-TX (10/100ME)
	Fa0/2	100BASE-TX (10/100ME)
	Gi0/3	100BASE-TX (10/100ME)
	Gi0/3	100BASE-TX (10/100ME)
	Gi0/4	100BASE-TX (10/100ME)
	Gi0/4	100BASE-TX (10/100ME)
	Fa0/5	100BASE-TX (10/100ME)
	Fa0/6	100BASE-TX (10/100ME)
	Fa0/7	100BASE-TX (10/100ME)
...

(This is from a Cisco 3560-48PS which has 48 fast ethernet ports and 4 gig sfp ports. When you do a sh int desc it shows as Fa0/1-48 then Gi0/1-4.)

If I just simply do this, there's no issue:
Fa0/[1-48]
Gi1/[1-4]

But doing that doesn't match the switch. It also appears that there is no issue actually adding the interfaces and they are there in the database correctly, I assume, but just not shown properly.

ps RIP issue title, I have no idea how to condense that down further.

**Comment by zevlag** [comment] 2017-01-05 23:09
I think this is a duplicate of #778 and #224.

**Comment by x-radeon** [comment] 2017-01-05 23:17
Oh sorry, I swear I searched, but I left the filters to is:issue is:open, that's why I didn't see 778 and I must of just skipped over 284.

But yes, it is duplicate of those.

**Comment by jeremystretch** [comment] 2017-01-06 02:58
No worries; there are quite a few issues to dig through. I'm hoping to have #284 sorted prior by the 1.9.0 release.

**Closed by jeremystretch** 2017-01-06 02:58 UTC
