### ISSUE TITLE
Device selection broken on 1.9.6 (IP creation)

### ISSUE THREAD

**Issue by Mmoi-Fr** [digitalocean/netbox#1123] opened 2017-05-02 13:29 UTC
We encounter a bug with Netbox, under release 1.9.6. 
As we are adding or editing an IP Address, we can’t assign it to a device. We’re able to select a site and a rack, but neither a device nor an interface.

We checked the browser console and saw that the request is been sent when we select the Site ("interface_rack: Fetching /api/dcim/racks/?site_id=XX"), but not on Rack selection.

Thanks for your work

**Comment by jeremystretch** [comment] 2017-05-02 15:47
Looks like a duplicate of #1101. Should be fixed in 1.9.7.

**Closed by jeremystretch** 2017-05-02 15:47 UTC
