### ISSUE TITLE
Feature Request - Power Calculation Per Rack

### ISSUE THREAD

**Issue by tomek0001** [digitalocean/netbox#818] opened 2017-01-19 23:30 UTC
It would be great if netbox would support power calculations of all devices installed in the rack. Basically planing on rack deployment but would like to make sure there is enough power for all of the devices. Cabinet would have total power capacity and any device type min/average/max power draw. 

Thanks

**Comment by jeremystretch** [comment] 2017-01-20 14:39
Duplicate of #54

**Closed by jeremystretch** 2017-01-20 14:39 UTC
