### ISSUE TITLE
Can't add network interface to Virtual Machine

### ISSUE THREAD

**Issue by 1stdemon** [digitalocean/netbox#1719] opened 2017-11-16 16:35 UTC
[ x] Bug report 

### Environment
* Python version:  3.4
* NetBox version:  2.2.5

Can't add network interface to Virtual Machine . To reproduce error you need add VM and then try to add Network Interface.

Request Method: | POST
-- | --
1.11.7
**AttributeError
'NoneType' object has no attribute 'device_type'**
/opt/netbox/netbox/dcim/models.py in clean, line 1260
/usr/bin/python3.4
3.4.5
['/opt/netbox/netbox',  '/opt/netbox/netbox',  '/usr/bin',  '/usr/lib64/python34.zip',  '/usr/lib64/python3.4',  '/usr/lib64/python3.4/plat-linux',  '/usr/lib64/python3.4/lib-dynload',  '/usr/lib64/python3.4/site-packages',  '/usr/lib/python3.4/site-packages']

**Comment by jeremystretch** [comment] 2017-11-16 16:40
Duplicate of #1717. Will be fixed in v2.2.6.

**Closed by jeremystretch** 2017-11-16 16:40 UTC
