### ISSUE TITLE
Rack Elevation print or export

### ISSUE THREAD

**Issue by elmmare** [digitalocean/netbox#1182] opened 2017-05-15 20:53 UTC
Issue type: feature request

It would be useful having a way to print  or export (pdf or image) the rack elevation.
One way could be an action button that display the rack elevation only in a new tab/window...
or directly generating the output with an additional parameter:
../dcim/rack-elevations/?q=&group_id=3&output=pdf | png

**Comment by jeremystretch** [comment] 2017-05-15 21:27
Marking this as a duplicate of #160. (Be sure to give that one your +1)

**Closed by jeremystretch** 2017-05-15 21:27 UTC
