### ISSUE TITLE
prefix status : assigned  

### ISSUE THREAD

**Issue by moolinet** [digitalocean/netbox#762] opened 2017-01-02 17:39 UTC
* Problem description:
When assigning a range to a customer I'm not interested in knowing how the IP addresses will be used. I just need to know that whom that range has been assigned to.
I could use the existing "active" status for this but this will not help for capacity planning as netbox still believes all IP addresses are free.

* Improvement request:
It would be usefull to be able to add a "assigned" status to a prefix and then mark the prefix as fully used. this would allow to correctly calculate actual available ip space.

* Alternatively:
When looking at the aggregate summary I see an utilization percentage corresponding to how much ip space has been allocated within an aggregate.
It would be practical to show the same utilization percentage at a container level (based on prefix assignation and not on IP reservation)

Thanks

**Comment by jeremystretch** [comment] 2017-01-03 15:25
I think you may be confusing the prefix and address objects. A prefix represents a network; an IP address is an individual address. NetBox tracks each independently. Both objects can be assigned a status of "active," which indicates that they are in use.

If you're assigning prefixes (networks) to customers and don't care about the usage of individual addresses within those prefixes, then there's no need to track them. Just look at the prefix utilization under its aggregates or a parent prefix. Does that make sense?

**Comment by moolinet** [comment] 2017-01-03 21:14
If you can display the prefix utilization then everything is fine!
But I can't find it.
The only place where I see utilization is at the aggregate level.

I'm using a freshly deployed NetBox via docker install
the web site tells me it's version 1.7.3
(I just saw you bumped version to 1.8 but I don't know how to upgrade
the docker install)

**Comment by jeremystretch** [comment] 2017-01-03 21:17
Sounds like a duplicate of #237 then. Please add any other comments/suggestion you have regarding this feature there. Thanks.

**Closed by jeremystretch** 2017-01-03 21:17 UTC
Labels: awaiting reply
