### ISSUE TITLE
Add 'Multiple selection' custom filed type

### ISSUE THREAD

**Issue by berahtlv** [digitalocean/netbox#2927] opened 2019-02-22 10:58 UTC
### Environment
* Python version:  3.5.4 -->
* NetBox version:  2.5.7 -->

### Proposed Functionality
Add multiple selection custom field type.

### Use Case
Select multiple custom field values in selection field. Useful when attribute can have multiple values.

### Database Changes
Some changes will be needed.

### External Dependencies
No additional.

**Comment by jeremystretch** [comment] 2019-02-22 14:01
Duplicate of #2522

**Closed by jeremystretch** 2019-02-22 14:01 UTC
