### ISSUE TITLE
Ability to add device visio stencil

### ISSUE THREAD

**Issue by th0ma7** [digitalocean/netbox#2441] opened 2018-09-18 13:05 UTC
### Proposed Functionality
For each device types have the ability to attach visio stencils for both front & back so that the detailed & rack views become more realistic and usable.  This way it would also tell the side of top-of-rack switches.

**Comment by jeremystretch** [comment] 2018-09-18 13:15
Duplicate of #1529. Please search first and use the provided templates before opening future issues.

**Closed by jeremystretch** 2018-09-18 13:15 UTC
