### ISSUE TITLE
Shared IP Addresses

### ISSUE THREAD

**Issue by jennec** [digitalocean/netbox#404] opened 2016-07-29 12:41 UTC
This may have been implemented already but I am having the following issue and wondered how I would get around it.

We have a number of device that share IP addresses between then.  Such as Virtual Management Addresses for SAN groups.  Currently I can turn off Enforce Uniqueness on the VRF and create an Virtual Interface on each device and assign the shared IP to that interface.  But this results in duplicate IP addresses showing the IPAM (one for each device). 

Is there a way to set individual IP addresses so that they can be shared between devices without creating duplicates?

**Comment by jeremystretch** [comment] 2016-07-29 13:17
Sounds similar to the concept of stacked switches. I'll mark this as a duplicate of #99 but let me know if you had something different in mind.

**Closed by jeremystretch** 2016-07-29 13:17 UTC
