### ISSUE TITLE
ValueError when API Post for New VLAN with Custom Fields

### ISSUE THREAD

**Issue by mattschwen** [digitalocean/netbox#1452] opened 2017-08-24 21:59 UTC
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.5
* NetBox version:  v2.1.3

### Description

When trying to add a new VLAN via API Post with Custom Fields, I get the following Error:
```
Traceback (most recent call last):
  File "add_vlan_netbox.py", line 64, in <module>
    main()
  File "add_vlan_netbox.py", line 60, in main
    (postVLAN(url))
  File "add_vlan_netbox.py", line 46, in postVLAN
    response = requests.post(url, headers=headers, data=payload).json()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 894, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

When I exclude custom fields, I am able to add the VLAN just fine.

I am using the following script to add new VLANs:

```python
# Python
# import pdb; pdb.set_trace()

import requests, json


def postVLAN(url):

	headers = {
		'Authorization': 'Token MYHIDDENTOKEN',
		'Accept': 'application/json',
		}

	payload = {
		'name': 'test', 
		'vid': '900', 
		"custom_fields": {
			"Notes": 'notes',
			"Data Classification": "restricted",
			"Compute Platform": "all",
			"Routing Device": "befw",
			"Zone": "int"
			},
		}

	response = requests.post(url, headers=headers, data=payload).json()
	print response
	return response


def main():
	'''
	Main function, calls on other functions, start of the script.
	'''
	netbox = 'netbox.corp.adobe.com'
	netboxVlans = '/api/ipam/vlans/'
	url = 'http://%s%s' % (netbox, netboxVlans)

	(postVLAN(url))


if __name__ == '__main__':
	main()
```

**Comment by lampwins** [comment] 2017-08-24 22:25
@mattschwen this works just fine for me when 
```
response = requests.post(url, headers=headers, data=payload).json()
```
is changed to 
```
response = requests.post(url, headers=headers, json=payload).json()
```
`data` is for form data where netbox is expecting a json payload.

**Comment by mattschwen** [comment] 2017-08-24 22:44
I have changed that line to:
`response = requests.post(url, headers=headers, json=payload).json()`

Here is my response in text formatL

```html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Server Error</title>
	<link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/font-awesome-4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-danger" style="margin-top: 200px">
                    <div class="panel-heading">
                        <strong>
                            <i class="fa fa-warning"></i>
                            Server Error
                        </strong>
                    </div>
                    <div class="panel-body">
                        <p>There was a problem with your request. This error has been logged and administrative staff have
                        been notified. Please return to the home page and try again.</p>
                        <p>If you are responsible for this installation, please consider
                        <a href="https://github.com/digitalocean/netbox/issues">filing a bug report</a>. Additional
                        information is provided below:</p>
<pre><strong>&lt;type &#39;exceptions.TypeError&#39;&gt;</strong><br />
&#39;custom_fields&#39; is an invalid keyword argument for this function</pre>
                        <div class="text-right">
                            <a href="/" class="btn btn-primary">Home Page</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>
```

**Comment by lampwins** [comment] 2017-08-24 22:51
Thanks, at this point this appears to be a duplicate of #1443 albeit extended to vlans.

**Comment by jeremystretch** [comment] 2017-08-25 01:23
Yeah, looks like it. I'm going to close this out as #1443 has been resolved in the develop branch and will be out in v2.1.4.

@mattschwen if you still have this issue once upgraded to v2.1.4 please ask to reopen this.

**Closed by jeremystretch** 2017-08-25 01:23 UTC
