### ISSUE TITLE
feature request: add 1/2 1U device (ideally 1/4, 1/2, 3/4)

### ISSUE THREAD

**Issue by alejojo** [digitalocean/netbox#535] opened 2016-09-07 03:30 UTC
Hi there,

would it be possible to add devices to a rack that can take, for example half 1U?

Example devices:

* [juniper srx110](http://www.juniper.net/uk/en/products-services/security/srx-series/srx110/) 
* [supermicro twin](https://www.supermicro.com.tw/products/nfo/1UTwinPro.cfm)

Both take half 1U. Supermicro has more options, like fattwin that are 4U/8Nodes

The following sizes would be perfect to cover all options:

* 1/4
* 1/2
* 3/4

thank you!

related #51

**Comment by alejojo** [comment] 2016-09-07 04:54
related #51

**Comment by jeremystretch** [comment] 2016-09-07 15:17
Duplicate of #51

**Closed by jeremystretch** 2016-09-07 15:17 UTC
