### ISSUE TITLE
Creating comment log / history for a device in netbox

### ISSUE THREAD

**Issue by mikili** [digitalocean/netbox#2304] opened 2018-08-04 12:15 UTC
**Environment**

- Python version: 3.6.5
- NetBox version: v2.3.6

i want to write an issue tracker history per device in netbox so that users can write and track any issue for each device.
for example:

______________________________
Jack:
device has been been updated.
______________________________
Mike:
Dear jack,
would you please update device.
______________________________

**Comment by jeremystretch** [comment] 2018-08-06 13:28
Thank you for your interest in NetBox. We require that all issues be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/tree/develop/.github/ISSUE_TEMPLATE). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the appropriate template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!

**Comment by jeremystretch** [comment] 2018-08-07 16:51
Duplicate of #151 anyway.

**Closed by jeremystretch** 2018-08-07 16:51 UTC
Labels: status: revisions needed
