### ISSUE TITLE
Interface assignment does not offer device selection anymore

### ISSUE THREAD

**Issue by jdecorniquet** [digitalocean/netbox#1639] opened 2017-10-23 20:00 UTC
###Issue type

[ ] Feature request
[X ] Bug report
[ ] Documentation

###Environment

Python version: 2.7..9
NetBox version: 2.2.2

###Description

Hello,

I must have missed something in the release notes but, we notice when editing an IP adresse assignement, on a device, we can't actually select another device (to change the assignement). See the screenshot below : 

<img width="788" alt="screen shot 2017-10-23 at 3 52 21 pm" src="https://user-images.githubusercontent.com/26890473/31910184-b7468f6c-b80a-11e7-9ea0-cc095bb0dcfc.png">

We use to have the possibility to make Interface Assignement directly when adding an IP address, the below fields do not exist anymore : 

<img width="788" alt="screen shot 2017-10-23 at 3 57 36 pm" src="https://user-images.githubusercontent.com/26890473/31910280-fa0c7b72-b80a-11e7-9c00-0bffbcb8b7d7.png">

Looks like it's gone since 2.2.0, is it related to the Virtualization module and therefor, not a bug ?

Regards,

**Comment by jeremystretch** [comment] 2017-10-23 20:04
Duplicate of #1512

**Closed by jeremystretch** 2017-10-23 20:04 UTC
