### ISSUE TITLE
Import DHCP IP ends up as Active

### ISSUE THREAD

**Issue by fourg** [digitalocean/netbox#682] opened 2016-11-11 04:41 UTC
When attempting to import a DHCP IP the IP's all show up as Active rather than DHCP.  Example of import format below which results in Active.

10.54.66.212/24,,,DHCP,,,,

**Comment by jeremystretch** [comment] 2016-11-11 04:50
Duplicate of #674, which was fixed just earlier today. Will be resolved in v1.7.1.

**Closed by jeremystretch** 2016-11-11 04:50 UTC
