### ISSUE TITLE
Implement discrete layer two domains with a site

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#111] opened 2016-06-29 15:15 UTC
Currently, a user can create multiple VLANs with the same VID and name within a site. This is allowed to provide the maximum flexibility when documenting real-world networks. However, it can also be very confusing, as there is no additional information to differentiate "VLAN 100 (ToR P2P)" from another "VLAN 100 (ToR P2P)," for example.

The proposal here is to implement a new model to represent a discrete zone within a site, within which each VLAN must have a unique VID (and name?). It should be fairly straightforward to extend the current schema to support this.

**Comment by mdlayher** [comment] 2016-06-30 20:06
https://github.com/digitalocean/netbox/issues/147 was filed recently as a duplicate of this issue.  Linking it here because it provides some great details that may be useful in designing this feature.

**Comment by rdujardin** [comment] 2016-07-12 10:56
Accordingly with #235, we could drop the VLAN site assignment and replace it with an optional discrete zone assignment, discrete zones being assigned to a site (maybe optionnally too) ?

**Closed** 2016-07-15 17:36 UTC
Labels: feature request, roadmap
