### ISSUE TITLE
Custom Fields not visible in v2.4.0

### ISSUE THREAD

**Issue by chelapa** [digitalocean/netbox#2360] opened 2018-08-15 20:56 UTC
### Environment
* NetBox version:  <v2.4.0>
* Python: <2.7.12>

### Steps to Reproduce
Click on any device or etc, non edit view cant see fields. edit view the fields are there

### Expected Behavior
See custom fields

### Observed Behavior
No Custom fields shown in non edit mode

**Comment by jeremystretch** [comment] 2018-08-15 20:57
Duplicate of #2308. Please upgrade to the most recent stable release.

**Closed by jeremystretch** 2018-08-15 20:57 UTC
