### ISSUE TITLE
DCIM interfaces API endpoint returns VM interfaces

### ISSUE THREAD

**Issue by JuergenKammer** [digitalocean/netbox#3036] opened 2019-04-03 10:11 UTC
### Environment
* Python version:  3.6.8
* NetBox version:  2.5.9

### Steps to Reproduce
1. Create a virtual machine with an interface.
2. Use the API to list interfaces (you may specifically search by name or whatever, just ensure that you get the interface at the virtual machine returned).

### Expected Behavior
The API returns the virtual-machine with the corresponding data, just like it does for a device if a returned interface belongs to a device.

### Observed Behavior
There is no reference to a virtual-machine returned. Instead the interface is returned with a "device: null" entry.

### Background
I realized this when I gathered up all interfaces via the API, keeping track of the devices: surprisingly I encountered multiple interfaces with the same name on the same "device", then realized they all belonged to the device "null". I realized, ok, no devices, these are virtual machines - but no virtual-machine data is returned.

In fact, this may even be deeper buried: "device" is a *required* field when doing a POST for an interface (see api_dcim_interfaces_create in api/docs/) . No way to specify a virtual machine instead, which should be there.

**Comment by Xelinor** [comment] 2019-04-03 23:50
I believe that is working as intended.

/api/virtualization/interfaces/ is what you are looking for, there is a separate API call for the virtual machine interfaces.

**Comment by JuergenKammer** [comment] 2019-04-04 07:08
Ah, right, I missed that, oups. But...

Should interfaces of virtual machines returned at all when querying for interfaces under /api/dcim/interfaces? To return them under /api/dcim/interfaces (with device = null) when they are under /virtualization/interfaces is not really helping (at least, it fooled me ;-o).

If I query under /api/virtualization/interfaces I *only* get the interfaces belonging to virtual machines, and not the interfaces under dcim with virtual-machine = null. To have a different behavior in these two trees seems inconsistent.

**Comment by jeremystretch** [comment] 2019-04-04 19:05
> Should interfaces of virtual machines returned at all when querying for interfaces under /api/dcim/interfaces?

No. Marking this as a bug.

**Closed** 2019-04-04 19:07 UTC
Labels: status: accepted, type: bug
