### ISSUE TITLE
Show child device's interfaces in parent device

### ISSUE THREAD

**Issue by hsychla** [digitalocean/netbox#823] opened 2017-01-20 14:04 UTC
We have a lot of network appliances that have a bay to add additional interfaces (like http://www.lannerinc.com/products/x86-network-appliances/rackmount/fw-8758).

We currently define the parent device type (fw-8758) with its GB-interfaces and a bay for the interface card. 
We then define a child device type for the interface card which is then added to parent device's bay. 

The problem is: after instantiating parent- and child-device and "inserting" the child device into the parent, I can not connect an interface or assign an IP to an interface of the interface card when looking at the parent device's page. 

IMHO, by inserting the interface card into the parent device, the interfaces become interfaces of the parent device and hence should be configurable from the parent device's page.

**Comment by jeremystretch** [comment] 2017-01-20 21:51
Device bays are only meant to house discrete, autonomous devices (for example, a chassis of blade servers). Components which do not provide their own control plane (for example, a line card in a chassis switch) should be installed as modules.

Incidentally, #824 was just opened to foster detailed discussion around this concept, so I'm going to mark this as a duplicate of that issue. Please feel free to share any additional thoughts there.

**Closed by jeremystretch** 2017-01-20 21:51 UTC
