### ISSUE TITLE
Don't see interfaces of devices under Cirtcuit section

### ISSUE THREAD

**Issue by thoms27** [digitalocean/netbox#642] opened 2016-10-26 16:58 UTC
Hi,

When I want to attach an interface to a circuit, I see the Site, Rack, Device but not the interfaces attached to this Device although under Device section I see the interfaces. Is it normal ?

Thanks in advance.

Regards,

Thomas Vahé

**Comment by jeremystretch** [comment] 2016-10-26 21:51
No, the interfaces should show up in the selection list once you select a device. Interfaces which are already connected will appear in the list but will be disabled.

**Comment by thoms27** [comment] 2016-10-27 07:28
Hi,

Below, the interface of my device, but nothing in the Circuit section:

Device :
![sans titre](https://cloud.githubusercontent.com/assets/20238377/19758207/5b33516a-9c27-11e6-89b2-3c17d26940ca.jpg)

Circuit :
![sans titre1](https://cloud.githubusercontent.com/assets/20238377/19758012/8334ed0a-9c26-11e6-8eda-9e15b8ef6b4e.jpg)

Have you got the same problem ?

Thanks in advance.

Thomas V.

**Comment by thoms27** [comment] 2016-10-27 07:35
In fact it doesn't works with a Virtual Interface. When I change the type to 1000 Base-TX for example it's works fine : 

![sans titre2](https://cloud.githubusercontent.com/assets/20238377/19758490/997c28a6-9c28-11e6-9340-7a4559237ccb.jpg)

**Comment by jeremystretch** [comment] 2016-10-27 20:06
Right. You can't physically connect anything to a virtual interface. That wouldn't make sense. You can only attach a circuit to a physical interface, just like in the real world. (You don't have one circuit connected to a port-channel interface, but rather two or more circuits each connected to independent physical interfaces which are logically grouped into a port channel.)

I'm going to close this out as this is intended behavior.

**Closed by jeremystretch** 2016-10-27 20:06 UTC
