### ISSUE TITLE
extend the size of the description field for Interface

### ISSUE THREAD

**Issue by shugotek** [digitalocean/netbox#3272] opened 2019-06-21 07:48 UTC
### Environment
* Python version:  3.6.7
* NetBox version:  2.6.0

### Proposed Functionality
Hello,

Currently the description field for an interface is limited to 100 Characters.
I think this limitation could be changed to 255 (255 is the most common limit for a description field).

Regards,
Shugotek

**Comment by jeremystretch** [comment] 2019-06-21 13:15
Duplicate of #3249

**Closed by jeremystretch** 2019-06-21 13:15 UTC
