### ISSUE TITLE
Add database backup/restore button

### ISSUE THREAD

**Issue by miklasz** [digitalocean/netbox#1306] opened 2017-06-30 21:28 UTC
hi, it would be nice to have some easy way to backup restore database, at the moment I use bash script, but would be so nice to have backup restore from the netbox page.

Many thanks

Bartosz

### Issue type:

**Python version:**
**NetBox version:**

**Comment by jeremystretch** [comment] 2017-06-30 21:30
Marking this as a duplicate of #567. Database backup it outside the scope of NetBox.

**Closed by jeremystretch** 2017-06-30 21:30 UTC
Labels: duplicate
