### ISSUE TITLE
Display enhancement for Custom field. 

### ISSUE THREAD

**Issue by a31amit** [digitalocean/netbox#2383] opened 2018-08-21 22:56 UTC
### Environment
* Python version:  3.4.x
* NetBox version:  2.4.3

### Proposed Functionality
Functionality or True/False bit on custom field which allow them to show in device page section or hide from there. But Show all of them in inventory tab section. 

I believe this way it can become more useful. 

### Use Case
Custom fields are great in netbox and can be used for many things. Also these can be increase signifcantly due to user wanted information in netbox which is even not advisable. However It would be great if there could have a Display flag on custom field so it show on /dcim/device/id device page if display flag is enabled but all of custom fields showed under inventory tab with custom field section below to Chassis section. 

We are using custom field for various information not every information in custom field is needed when someone open a device page. But they are useful sometimes when someone needed detailed information about device. 

Example - 
I have these 5 custom fields - 

these are needed some point but not regularly. we calucalte a depreciation on device based on these dates and update end of life status which is TRUE/FALSE

Device Manfacture Date
First Production Date
Last reprovision Date
End of Life Date
End of Life Status

So End of life status and end of life date can be showed in Device Page but all other custom field can be showed into inventory tab, down below chassis section. it makes device home page much clean and nicer while using custom fields too. 

### Database Changes
Not sure at about this, I believe a true/false flag needed so that templates render them based on it.
This would be requires to change html template.

### External Dependencies
None

**Comment by Bill-Irvine** [comment] 2018-08-22 01:37
Something simple that might help in the mean time. 

I've changed the 'custom_fields_panel.html' template to only display used custom fields when viewing the device. This means you can fill out separate fields for different types of devices and it will only display the relevant ones.

`{% for field, value in custom_fields.items %}
	**{% if value is not None  %}**
                <tr>
                    <td>{{ field }}</td>
                    <td>
                        {% if field.type == 300 and value == True %}
                            <i class="glyphicon glyphicon-ok text-success" title="True"></i>
                        {% elif field.type == 300 and value == False %}
                            <i class="glyphicon glyphicon-remove text-danger" title="False"></i>
                        {% elif field.type == 500 and value %}
                            <a href="{{ value }}">{{ value|truncatechars:70 }}</a>
                        {% elif field.type == 200 or value %}
                            {{ value }}
                        {% elif field.required %}
                            <span class="text-warning">Not defined</span>
                        {% else %}
                            <span class="text-muted">N/A</span>
                        {% endif %}
                    </td>
                </tr>
	**{% endif %}**
{% endfor %}`

**Comment by jeremystretch** [comment] 2018-08-22 14:43
Sounds like a duplicate of #2132

**Closed by jeremystretch** 2018-08-22 14:43 UTC
