### ISSUE TITLE
Mark IPs used or available

### ISSUE THREAD

**Issue by rekkoner** [digitalocean/netbox#252] opened 2016-07-10 05:54 UTC
Ability to mark IP addresses available or in use would be helpful for monitoring environment.

This pertains mainly to the IP Address main screen (from the 'IP Space' menu), but would apply on other similar screens, such as from the IP Addresses tab of the Prefixes screen.

**Comment by jeremystretch** [comment] 2016-07-10 18:11
Any IP defined in NetBox should be considered to be used; available IPs are simply not defined.

There's a separate issue (#87) for marking IPs as reserved, so I'm going to mark this as a duplicate of that one.

**Closed by jeremystretch** 2016-07-10 18:11 UTC
