### ISSUE TITLE
Clarify utilization percentages for prefixes

### ISSUE THREAD

**Issue by Zimeon-** [digitalocean/netbox#1721] opened 2017-11-17 08:40 UTC
### Issue type
[ ] Feature request 
[X ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.5
* NetBox version:  v2.2.6

### Description
When viewing a prefix, that has all IPv4 host addresses used, it still shows the prefix as not fully utilized. For example in a /26 subnet, with all 62 host addressed utilized, it shows the prefix as 96% full. 

Would propose that the subnet utilization calculation to be changed, so that the broadcast and network addresses are not calculated when showing the subnet utilization.

Also regarding to https://github.com/digitalocean/netbox/issues/1669, when the block is full it will default back to network address. Perhaps remove the add ip-address option when a subnet is fully utilized from a host perspective. Imho any network stuff would be documented in the prefix, not in the network ip or broadcast ip.

**Comment by DirtyCajunRice** [comment] 2017-11-20 16:40
@Zimeon- I cannot reproduce this issue. Do you have "Is a pool" checked on that subnet?

**Comment by Zimeon-** [comment] 2017-11-21 09:08
https://imgur.com/BYrEk6c

**Comment by DirtyCajunRice** [comment] 2017-11-22 01:24
Yes, this is the intended behavior when "is pool" is checked. It allows the allocation of broadcast and network IPs. If you uncheck "is pool" in that subnet's settings you will get your desired 100% utilization.

**Comment by jeremystretch** [comment] 2017-11-22 17:38
I've marked this as a bug because the way we show utilization right now isn't clear. The "utilization" attribute of the prefix view always lists the number of child IP addresses it contains, but the utilization percentage is calculated differently for container and non-container prefixes.

I've moved the IP count to the "IP addresses" tab at the top, and replaced the attribute with the utilization graph that's displayed in the prefixes list.

**Closed** 2017-11-22 18:00 UTC
Labels: bug
