### ISSUE TITLE
Feature Request - Rack unit direction

### ISSUE THREAD

**Issue by dyordanovv** [digitalocean/netbox#379] opened 2016-07-25 09:06 UTC
Hello, 
some of our racks have their units start with 1 in the bottom of the rack and some start with unit 1 on the top of the rack. It would be very useful if we can choose the directions for the units per rack bottom to top or top to bottom.

**Comment by jeremystretch** [comment] 2016-07-25 13:43
Duplicate of #191

**Closed by jeremystretch** 2016-07-25 13:43 UTC
