### ISSUE TITLE
Can't expand each ip_prefix, only expand all

### ISSUE THREAD

**Issue by zeomegazord** [digitalocean/netbox#977] opened 2017-03-21 10:54 UTC
### Issue type:
feature request

**Python version:**
2.7
**NetBox version:**
1.9.0

I can't expand needed ip_prefix if I click on triangle near ip_prefix. I can expand all ip_prefixes only. It's very unuseful. Could you please fix it.

**Comment by jeremystretch** [comment] 2017-03-21 12:55
Duplicate of #55. This is intended behavior (for now).

**Closed by jeremystretch** 2017-03-21 12:55 UTC
