### ISSUE TITLE
Cable Plant suggestion

### ISSUE THREAD

**Issue by amezibra** [digitalocean/netbox#376] opened 2016-07-24 13:03 UTC
An idea for implementing Cable Plants:

introduction of CircuitPath object.

- CircuitPath attributes can be created by user as for other objects..
- a CircuitPath is an ordered set of circuit and device (active or inactive).
- a CircuitPath would have an entry interface endpoint A and and exit interface endpoint Z
- a CircuitPath X can be created from multiple CircuitPath (A,B,C..) 
- A boolean toggle can enforce that some attribute match before aggregating CircuitPath (interface type/vlan/dlci/vcid/Wavelenght etc..)
- attribute of Parent CircuitPath like Speed/QoS/CIR/MTU/etc.. could be inherited from the lowest common denominator in the Path.
- a filter would allow to make diagram including or not CircuitPath detail.

thanks for your awesome tool.

**Comment by jeremystretch** [comment] 2016-07-25 14:06
Duplicate of #20

**Closed by jeremystretch** 2016-07-25 14:06 UTC
