### ISSUE TITLE
Add VLAN to devices without IP addresses

### ISSUE THREAD

**Issue by aronpc** [digitalocean/netbox#755] opened 2016-12-23 13:42 UTC
Hello netbox maintainers.

I have PPPoE concentrators that has many access VLANs without ip, I haven't found a way to add the VLANs on an interface to such equipment. 

Thanks for all

**Comment by jeremystretch** [comment] 2016-12-23 16:15
Marking this as a duplicate of #150, but to be honest I don't think it's very likely to be implemented. Tracking VLAN assignments to individual interfaces would introduce a lot of overhead with little benefit.

**Closed by jeremystretch** 2016-12-23 16:15 UTC

**Comment by Beiriz** [comment] 2016-12-23 17:38
This is very important for our PPPOE hubs. We use several VLANs linked to BRIDGES. They serve to aggregate customers by geographical areas and to facilitate the relocation of IP blocks between these equipments.Thank you :)
