### ISSUE TITLE
Server Error on rack elevations

### ISSUE THREAD

**Issue by rgrueebler** [digitalocean/netbox#2842] opened 2019-02-01 13:28 UTC
Hi everyone,

After the upgrade to the version 2.5.4 I receive an error when I click on Racks > Elevations.

### Environment
* Python version:  3.6.7
* NetBox version:  2.5.4

### Steps to Reproduce
1. Click on 'Racks'
2. Click on 'Elevations'
![screen shot 2019-02-01 at 14 21 15](https://user-images.githubusercontent.com/6319208/52125629-61573600-262d-11e9-82ff-3fead0382f4f.png)
3. The following error message shows up
![screen shot 2019-02-01 at 14 21 03](https://user-images.githubusercontent.com/6319208/52125684-864ba900-262d-11e9-8998-f3ab569f7fe0.png)

Thanks
Remo

**Comment by jeremystretch** [comment] 2019-02-01 13:55
Duplicate of #2824, fixed in v2.5.5

**Closed by jeremystretch** 2019-02-01 13:55 UTC
