### ISSUE TITLE
Server error when searching for an IP address in 2.1.1

### ISSUE THREAD

**Issue by cmccallan** [digitalocean/netbox#1394] opened 2017-08-04 10:23 UTC
### Issue type:

**Python version:2.7
**NetBox version:2.1.1

After upgrading to 2.1.1, we're seeing an error when searching for IP addresses. Tested an upgrade from 1.8.2 to 2.0.4 and issue wasn't present, error and debug logs attached with what we're seeing. Prefixes and other searches are fine, just IP addresses we're seeing it.

![error](https://user-images.githubusercontent.com/8103709/28965082-60e8d3ec-7907-11e7-93d5-e3de02320923.png)

[error.txt](https://github.com/digitalocean/netbox/files/1200002/error.txt)

**Comment by jeremystretch** [comment] 2017-08-04 13:14
Duplicate of #1388. Will be fixed in v2.1.2.

**Closed by jeremystretch** 2017-08-04 13:14 UTC
