### ISSUE TITLE
Create another device view should probably assume previous settings (configurable?)

### ISSUE THREAD

**Issue by patrick-livestream** [digitalocean/netbox#886] opened 2017-02-08 17:26 UTC
When clicking on create another, it seems like it'd be faster to just assume similar settings from the previous creation (like orientation, rack, etc..) but unique items like position would need to be filled in.

(adding as an issue to see if there's desire for the feature, before I work on the PR)

**Comment by jeremystretch** [comment] 2017-02-08 18:16
Duplicate of #648

**Closed by jeremystretch** 2017-02-08 18:16 UTC

**Comment by patrick-livestream** [comment] 2017-02-08 18:19
Sorry! I thought I'd searched for it but must have missed it. Thanks @jeremystretch
