### ISSUE TITLE
Multiple Outside NAT's for one IP

### ISSUE THREAD

**Issue by traveler3468** [digitalocean/netbox#1280] opened 2017-06-16 13:19 UTC
Could it be possible to allow a feature that would make it possible to assign multiple outside NAT's to a single inside address? My organization has servers that connect to different outside services where the server address is NAT'd to different IP addresses based on the service it is communicating with. I would like to be able to see at a glance the many NAT's that the server is currently assigned by viewing the IP address page.

**Comment by jeremystretch** [comment] 2017-06-16 13:22
Duplicate of #1202

**Closed by jeremystretch** 2017-06-16 13:22 UTC
