### ISSUE TITLE
Search: open result directly when only one result is found

### ISSUE THREAD

**Issue by aswen** [digitalocean/netbox#2917] opened 2019-02-20 12:25 UTC
### Environment
* Python version: Don't know 
* NetBox version: bcf91b9edb4b (v2.5.6) 

### Proposed Functionality
When only one result is found in search it saves a click if Netbox would open that object rather than showing the list. That saves some time.

### Use Case
The quickest way to a device is via search, it would save time to go to it directly if you know the name.

**Comment by jeremystretch** [comment] 2019-02-20 14:47
Duplicate of #2668

**Closed by jeremystretch** 2019-02-20 14:47 UTC
