### ISSUE TITLE
OOB Management Interfaces being grouped with normal Interfaces

### ISSUE THREAD

**Issue by aaronkrzywicki** [digitalocean/netbox#1653] opened 2017-10-27 16:11 UTC
### Issue type
[x] Bug report      

### Environment
* NetBox version:  14a2f0c015ab (v2.2.2)
![screenshot from 2017-10-27 10-58-33](https://user-images.githubusercontent.com/12716923/32113829-28b2ae84-bb07-11e7-9e48-e2368192e8a5.png)

### Description
OOB Management Interface functionality not working as expected. When OOB Management radio button is selected for a new interface it shows in the group of normal interfaces.

This behavior is unexpected as far as I can tell. Expected behavior would be interfaces created with the OOB Management radio button checked should be grouped in their own Management Interfaces group independent of the main interfaces.

**Comment by aaronkrzywicki** [comment] 2017-10-27 16:30
It's also not possible to add a management interface to a PDU or console server without also marking the device as a network device. especially when that check box specifically says "This device has NON-MANAGEMENT network interfaces".

However
<img width="245" alt="upload 4" src="https://user-images.githubusercontent.com/12716923/32114849-3ea56d00-bb0a-11e7-8821-6e6979c89080.png">
 you can designate a PDU or console server as a network device, add the management interface, then remove the network device designation and the management interface stays.

**Comment by jeremystretch** [comment] 2017-10-30 21:41
> OOB Management Interface functionality not working as expected. When OOB Management radio button is selected for a new interface it shows in the group of normal interfaces.

This is intended behavior. Management interfaces used to be grouped separately but were merged with normal interfaces a while back to simplify the UI.

> It's also not possible to add a management interface to a PDU or console server without also marking the device as a network device. especially when that check box specifically says "This device has NON-MANAGEMENT network interfaces".

This wording is outdated and should be fixed. Anything with a network interface is considered a network device.

> However you can designate a PDU or console server as a network device, add the management interface, then remove the network device designation and the management interface stays.

This is intended behavior. Modifying a device type does not retroactively alter any associated devices.

**Closed** 2017-10-30 21:47 UTC
Labels: bug
